### ISSUE TITLE
WalletConnect in new Bridge no longer works (with Gnosis Safe)

### ISSUE THREAD

**Issue by tacryt-socryp** [urbit/bridge#1006]
No transactions are able to go through.

<img width="1191" alt="Screen Shot 2022-03-23 at 4 45 37 PM" src="https://user-images.githubusercontent.com/1377557/159801235-7a4997d2-99c3-42d8-a439-fd97c12e5897.png">

**Comment by tacryt-socryp** [comment]
Logging in to Bridge using WalletConnect now works properly, but now when I try to send a transaction it silently fails with no errors in the console. Nothing at all happens when clicking "Set Networking Keys" button for a star.

**Comment by nerveharp** [comment]
Fixed by urbit/bridge#1008

**Comment by lukestiles** [comment]
Closing as fixed per comment above.

**Comment by lukestiles** [comment]
PR not merged, re-opening
