### ISSUE TITLE
Key mismatch error when booting

### ISSUE THREAD

**Issue by ixv** [urbit/bridge#1011]
After accepting a planet via invite code, I successfully signed in to bridge to download my networking keys, but when I tried to boot my ship I got
```
urbit 1.8
boot: home is /home/isaac/ships/wicnys-rontev
loom: mapped 2048MB
lite: arvo formula 27e494c5
lite: core 7b144622
lite: final state 7b144622
boot: downloading pill https://bootstrap.urbit.org/urbit-v1.8.pill
boot: retrieving ~wicnys-rontev's public keys
boot: verifying keys
boot: invalid keys for planet '~wicnys-rontev'
pre-boot error: %key-mismatch
```

@nerveharp

**Comment by nerveharp** [comment]
@tomholford More key silliness...

**Comment by tomholford** [comment]
@ixv What was the approximate time delta between when the invite was accepted and when the boot was attempted?

**Comment by ixv** [comment]
I guess it was too quick, I just tried booting again and it worked

**Comment by thelifeandtimes** [comment]
I'm running into this still; do we know about how long the key propagation takes? and might it be worth adding some UI element to inform users of their entry into a world of `calm computing`?
