### ISSUE TITLE
No keyfile included when downloading master ticket

### ISSUE THREAD

**Issue by tacryt-socryp** [urbit/bridge#1023]
https://twitter.com/SadeBaeza/status/1530376196931739648?s=20&t=9mT0JDpbopJRySmTj-Wr_w

**Comment by tacryt-socryp** [comment]
Hi there, this issue is still live. What's the deal here?

**Comment by zalberico** [comment]
Closing as duplicate of https://github.com/urbit/bridge/issues/1010
