### ISSUE TITLE
Invite csv never finishes generating

### ISSUE THREAD

**Issue by wbsquared** [urbit/bridge#1032]
**Describe the bug**
I get invites done for my L2 star ~nilref through a proxy planet ~rigbel-waldex with a master key for that planet.

For the past few weeks I have been unable to download the csv file because it remains in a neverending loop of counting invites and then counting again. The download button never appears. Can you help me fix this? I have tried different computers and browsers and have cleared cookies many times without any luck.

Addendum: since submitting the original email I tried again on another computer and the count goes up to about 3100 invites total, and actually this time did finish, but in the end only let me download a CSV of 1849 invites.  I have at least one prior invite file of more than 2000 invites, and very few have been activated so I know that for sure 1849 is incorrect, and the correct amount is probably around the 3100 or so that it counted up to.

**To Reproduce**
1. Go to 'bridge..'
2. log in as proxy planet with code
3. click on nilref star, click on invites, wait until count is complete (or sometimes it never completes, continues to restart and count and you never get the CSV file download button to appear). This is the error.

**Expected behavior**
I should be able to reliably click on the star, and have it easily generate my entire list of planets sequentially and without delay and then get to the end and I can dowload the complete list of all planets generated..

**Screenshots**
I am happy to do screenshots if you think it will help. I think the description above is fairly precise.

**Desktop (please complete the following information):**
 - OS:Windows 10
 - Browser chrome, but is also seen on brave

**Smartphone (please complete the following information):**
N/Q

**Login method (please complete the following information):**
Bridge master ticket of rigbel-waldex, the proxy for nilref

0x2299b68a5369ae2e0ab0f650e42ce33e5aa69e83

**Additional context**
I also have some planets from this star spawned via a Metamask access. in the past this seemed to be causing issues.

**Comment by wbsquared** [comment]
Looking forward to getting a response. FYI this output from the Astrolabe app in Urbit seems to be correct.

 
![Screenshot 2022-07-16 15 06 56](https://user-images.githubusercontent.com/35438364/179373338-9de6af42-f053-4543-8631-9644d890e58b.png)

**Comment by lukestiles** [comment]
Closed as the invite flow is no longer supported.
