### ISSUE TITLE
Can't retrieve keyfile or passport to boot new L2 planet

### ISSUE THREAD

**Issue by m-rio** [urbit/bridge#1047]
I'm not being able to boot a planet due to lack of keyfile. 

I recently acquired an L2 planet and the first thing I did was login to bridge using the master ticket and to transfer via ownership address "transfer" button.

After an hour or so I saw on the receiving address (while logged in via brave browser) I could accept the transfer. I then looked for the the keyfile and the passport zip but couldnt find either. The keyfile button is greyed out saying "Keyfile unavailable" (see in screenshot below).

I'm lost as to what I can do so I posted a few screenshots of the state of bridge to see if someone here can explain what happened and how can I get the keyfile and passport.

![image](https://user-images.githubusercontent.com/41305636/191878070-abc1c493-1f6f-4a19-b907-8dfcae814517.png)
![image](https://user-images.githubusercontent.com/41305636/191878228-3b7ae0de-70be-4546-a3b6-743b5910746f.png)
![image](https://user-images.githubusercontent.com/41305636/191878265-69d8b777-10db-4b83-9a28-059d19db2573.png)
![image](https://user-images.githubusercontent.com/41305636/191878339-3657fa90-0009-4bed-8031-073644f1f395.png)

**Comment by Fang-** [comment]
> I recently acquired an L2 planet and the first thing I did was login to bridge using the master ticket and to transfer via ownership address "transfer" button.

This is important. The planet was configured for use with the master ticket. The networking keys (keyfile) was deterministically derived from the master ticket. Transferring the planet did not change the networking keys. But now, logging in with something other than the master ticket, it's no longer possible to know/derive the keyfile.

You will want to hit "reset" for the networking keys. This should re-generate them, letting you download the keyfile for the new keys.

The passport I believe is only available when logging in with a master ticket. You shouldn't need it as long as you have the login details of the current ownership address.

**Comment by m-rio** [comment]
thanks @Fang- , eventually I did hit the reset "networking keys" option (I was afraid of doing so as I didn't get if it would cost gas or not or break something). I am up and running! thank you!
