### ISSUE TITLE
Stale keyfile presented for download after breach

### ISSUE THREAD

**Issue by belisarius222** [urbit/bridge#1068]
**Describe the bug**

I recently breached my ship.  After the eth transaction said it was complete, I clicked to download the keyfile, and it downloaded "rovnys-ricfer-4.key".  I then booted a fresh ship, but it couldn't talk to anyone on the network.  I eventually logged back into bridge, clicked to download the keyfile, and it downloaded "rovnys-ricfer-5.key".  I then killed the ghost ship, booted fresh with the new keyfile, and it worked fine.

**To Reproduce**
1. Breach a ship.
2. Click on 'download keyfile'
3. waste some time trying to boot a ship with the stale keyfile
4. download the new keyfile, delete ghost ship, boot fresh ship

**Expected behavior**
The keyfile download should download the new file after a breach, not the old one.

**Desktop (please complete the following information):**
 - OS: MacOS 12.4 
 - Browser: safari

**Login method (please complete the following information):**
master ticket

**Comment by tomholford** [comment]
Fix for this (v3.2.1) is in production
