### ISSUE TITLE
"Unhandled Rejection (Error): connection not open" in development w/local node

### ISSUE THREAD

**Issue by jtobin** [urbit/bridge#107]
Does anyone else observe this?  I see it in both Brave and Chrome.  It must be a pretty recent thing.

![](https://dsh.re/4c2c3)

(This is after choosing 'Local Node' and authing with mnemonic after an `npm run pilot`.)

**Comment by Fang-** [comment]
The branch I'm working on include up to bf5e9bb and I haven't seen that.

Are you sure it's not opening ganache on a different port because default was already taken?

**Comment by c-johnson** [comment]
This when we changed switch to secure websockets (ws:// to wss://) for localnode. I've got a task to figure out how to make wss:// work locally; for now, changing it to ws:// should get you through.

**Comment by jtobin** [comment]
@c-johnson You are correct my good man, that did the trick.  I'll PR a special-case fix for development in the interim.
