### ISSUE TITLE
Can we use standard Eth wallet NFT transfer functions to transfer (L1) Azimuth points?

### ISSUE THREAD

**Issue by m-rio** [urbit/bridge#1074]
Say we purchased L1 Azimuth points in OpenSea. We now have the point in our eth wallet. Can we use the NFT transfer function to transfer the point to another wallet or do we need to use Bridge for this operation?

**Comment by Fang-** [comment]
L1 Azimuth points support the ERC721 NFT standard, and as such should be transferable through other wallet software. You don't strictly need to use Bridge to do transfers in most cases. Of course, we can make no guarantees about that other software.

It's also worth noting that using the standard/generic transfer functionality, your point will _always_ be reset. Its networking keys will be set to zero, and it will be flagged as having [breached](https://operators.urbit.org/manual/id/guide-to-resets). If you are presently running an Urbit using that ID, this may be undesirable.

**Comment by m-rio** [comment]
Your second paragraph is very clarifying. It may be worth mentioning this in the [bridge guide](https://operators.urbit.org/manual/id/using-bridge). 

I supposed that when we use bridge we can set the "Retain proxies and key configuration, in case of transferring to self" flag, whereas using another wallet to transfer we can't which means we will always "breach" the urbit id.
