### ISSUE TITLE
dev: can't install Bridge dependencies

### ISSUE THREAD

**Issue by yosoyubik** [urbit/bridge#1096]
**Describe the bug**

Can't install Bridge dependencies

**To Reproduce**
Run `npm i` on a freshly cloned instance of the urbit repo (both on Mac and Ubuntu), using nvm 14.17.

I tried also removing package-lock.json to see if that was succesful but no luck.

Here's the extended output:

https://gist.github.com/yosoyubik/ff2647bafb944882c395694568938397

**Comment by tomholford** [comment]
@yosoyubik Thanks for flagging this issue. Just did a clean repo checkout + install on a Macbook Air M2 and it seems to be working as expected. Worth noting that I am using node 16.18.0. Can you give that a shot and report back?

For reference, here's the steps I followed (using [nvm](https://github.com/nvm-sh/nvm)):

```sh
nvm install 16.18.0
nvm use 16.18.0
npm install -g truffle
npm install
npm run build
```

**Comment by vvisigoth** [comment]
@yosoyubik can I close this?

**Comment by yosoyubik** [comment]
Yes, this was an issue from a migration from another macbook
