### ISSUE TITLE
Migrate to WalletConnect v2

### ISSUE THREAD

**Issue by stephenlacy** [urbit/bridge#1098]
WalletConnect is [sunsetting their v1](https://medium.com/walletconnect/weve-reset-the-clock-on-the-walletconnect-v1-0-shutdown-now-scheduled-for-june-28-2023-ead2d953b595) at the end of June 2023. This will effectively stop connect support for any v1 dapp/wallet.

Effective migration is to upgrade the walletConnect hook to use the v2 client.

**Comment by tomholford** [comment]
Thanks @stevelacy, adding this to my queue of outstanding items
