### ISSUE TITLE
Only accept incoming connections from localhost

### ISSUE THREAD

**Issue by abliss** [urbit/bridge#11]
When I followed the directions, it opened up the bridge UI to everyone on my network. Probably it should only listen on 127.0.0.1 rather than on 0.0.0.0.

**Comment by jtobin** [comment]
The following (using Python 3.4 and up) will serve the `build` directory on 127.0.0.1 alone:

```
python3 -m http.server 5000 --bind 127.0.0.1 --directory build
```

We could add this one to the instructions on next release @iamwillkim @gavinpatkinson.

**Comment by iamwillkim** [comment]
Resolved in newest release.
