### ISSUE TITLE
"Set public keys" vs "Set network keys"

### ISSUE THREAD

**Issue by msutherl** [urbit/bridge#119]
This should probably say "set network keys" rather than "set public keys," which is non-specific.

<img width="388" alt="Screenshot 2019-04-19 11 41 3" src="https://user-images.githubusercontent.com/31774/56438533-1053f700-6298-11e9-93ed-a3a10ea963e1.png">

**Comment by Fang-** [comment]
I was going to fight you on this, but the current flow doesn't let you set custom keys and assumes you're gonna want the arvo keyfile... so yes, I guess they are networking keys.

**Comment by msutherl** [comment]
@Fang- ahh, I see – this is the result of misplaced Azimuth maximalism. Caught in the act!

**Comment by Fang-** [comment]
Rather, it's a leftover from back when Bridge still had a bright future as "generic Azimuth management tool" ahead of it. rip ):

**Comment by cxk280** [comment]
I've just been setting up a star via Bridge, and the [getting started guide](https://urbit.org/docs/getting-started/using-bridge/) says the link should say `Set Urbit networking keys`. I'm not sure I'm the only one this has/will confuse. @msutherl pointed this out to me via email but thought I'd note my experience here.

**Comment by Fang-** [comment]
@msutherl do we agree on "set networking keys" for the exact phrasing? If yes, I'll go and patch that up in both Bridge and docs.

**Comment by msutherl** [comment]
@msutherl I think it should be "set network keys". "Networking keys" doesn't match the spec.

**Comment by rmariani** [comment]
Sounds good to me

**Comment by msutherl** [comment]
We gotta get this fixed. It's very confusing for people to see "set network keys" in the documentation, where Bridge only has a "set public keys" option.
