### ISSUE TITLE
Generated transactions throw an "invalid sender" error

### ISSUE THREAD

**Issue by juped** [urbit/bridge#12]
Trying to set networking keys for `~maldeb-hapben`. I'm using the management proxy, which is a Ledger, if that's important. According to Bridge, the chainId is 1 in the transaction; disassembling the raw tx seems to suggest the chainId is 28 (!).

**Comment by juped** [comment]
28 is `0x1c`, fwiw, in case a typo might be implicated (unlikely)

**Comment by juped** [comment]
nvm I went and read EIP-155 - it may just not be being set for ledger? see https://github.com/LedgerHQ/ledgerjs/issues/43#issuecomment-366984725

I don't do Javascript; this is my limit

**Comment by yiryan** [comment]
I experienced same problem - it's encoding as a hex string instead of an interger i.e. "0x" prefix on gasprice, gaslimit, chainID, when generating the transaction

**Comment by rcrdlbl** [comment]
I've also just experienced this issue

**Comment by jtobin** [comment]
@rcrdlbl #26 has a fix, and AFAIK should make it into the next release.
