### ISSUE TITLE
Implications of key change need to be communicated better

### ISSUE THREAD

**Issue by Fang-** [urbit/bridge#132]
I've seen a couple people smash the "rekey" button as soon as something was up with their networking. Worse, it wasn't at all obvious they needed to follow up by putting the new private keys into their Urbit.

Bridge should maybe do a better job of communicating, "if you change these, make sure to give the keyfile to anything that uses this identity" or similar.

Further thoughts?

**Comment by shrugs** [comment]
I've added a small note to the post-networking-keys-cycle flow, but agreed that this should have more design thought put into it.
