### ISSUE TITLE
Back button is broken on star <- galaxy

### ISSUE THREAD

**Issue by mrdomino** [urbit/bridge#136]
To reproduce:

1. Select “View a point”.
2. Pick any galaxy, say `~zod`.
3. Select “Details” for a star, say `~marzod`.
4. Navigate back in the browser (I tried in Firefox and Chrome on OS X).

Expected: I’m at the page for `~zod`.
Actual: I’m at the welcome page.

**Comment by jtobin** [comment]
I suspect this is the issue I highlighted [here](https://github.com/urbit/bridge/pull/86#issuecomment-475897713).

**Comment by shrugs** [comment]
fixed as part of #152 in the `mino` branch. lmk if we should keep issues open until they land in master or close them as they're fixed in the dev branch?

**Comment by Fang-** [comment]
Probably keep open until done in a release version, but definitely good to comment when things are in pipeline. (:
