### ISSUE TITLE
Documentation and instructions unclear

### ISSUE THREAD

**Issue by dpc** [urbit/bridge#14]
https://urbit.org/docs/getting-started/ says: 

> Click the link that says Set Urbit networking keys. Bridge will let you either download a keyfile derived from your networking keys are you can paste in your own network seed and derive a new keyfile. See our HD Wallet Spec for more information. 

http://localhost:5000/ says:

>Please enter a network seed for generating and setting your public network authentication and encryption keys. Your network seed must be a 32-byte-long hexadecimal string.

If you've authenticated with a master ticket or management proxy mnemonic, a seed will be generated for you automatically.

In both cases it is unclear what is the network seed. No seed was generated for me in the UI. Am I supposed to randomly generate one? Or does it have to be a specific one? 

There should be more instructions and explanation or something.

**Comment by xastor** [comment]
I also have a hard time determining what I should enter here..  Should I generate a string?  I also received a ticket with my planet.  Can this be used as network seed (in haxadecimal form)?

**Comment by dpc** [comment]
@xastor My understand now is that the seed is used to generate the public and private keys that your ship is actually going to use ("working keyset"). The public key is registered on the blockchain by your master Eth identity that owns the ship/start, so that people know which keys should they trust during normal operations.

I went with a random one. Eg. `openssl rand -hex 32`. Just make sure to not accidentally loose it, though I believe you can always overwrite the seed in the future. It's just another Eth transaction, and possibly a hassle and small disruption in communication. 

After #9 is implemented, this seed could be generated automatically from your master wallet seed, to save people the effort of generating and remembering it. But right now we have to do it manually.

**Comment by jtobin** [comment]
> I went with a random one. Eg. openssl rand -hex 32. Just make sure to not accidentally loose it, though I believe you can always overwrite the seed in the future. It's just another Eth transaction, and possibly a hassle and small disruption in communication.

That's correct, it's a very minor thing.

> After #9 is implemented, this seed could be generated automatically from your master wallet seed, to save people the effort of generating and remembering it. But right now we have to do it manually.

I'm surprised that network seeds aren't auto-generated for stars when authenticating via master ticket.  Let me check on that.

**Comment by dpc** [comment]
> > I went with a random one. Eg. openssl rand -hex 32. Just make sure to not accidentally loose it, though I believe you can always overwrite the seed in the future. It's just another Eth transaction, and possibly a hassle and small disruption in communication.
> 
> That's correct, it's a very minor thing.
> 
> > After #9 is implemented, this seed could be generated automatically from your master wallet seed, to save people the effort of generating and remembering it. But right now we have to do it manually.
> 
> I'm surprised that network seeds aren't auto-generated for stars when authenticating via master ticket. Let me check on that.

With hardware wallet, for a planet. That's what I've tried.

**Comment by jtobin** [comment]
I'm going to mark this as resolved as it appears the docs have improved in this area.
