### ISSUE TITLE
Dependency Proposal: unstated-next

### ISSUE THREAD

**Issue by shrugs** [urbit/bridge#160]
I'd like to add `unstated-next` to help standardize/de-duplicate some of the code I'm writing for pulling the global state out of our props chain.

I've basically just been writing the unstated code ([which is like 20 lines of typescript](https://github.com/jamiebuilds/unstated-next/blob/master/src/unstated-next.tsx)) already, so adding `unstated` is really just sugar for what we're already doing.

1. We re-implement unstated (as we already are) and avoid a dependency.
2. We add `unstated-next` and get to clean up a few lines of duplicated code within the `/store` directory.

**Comment by Fang-** [comment]
This seems innocent enough? The boilerplate in the `/store` file doesn't seem particularly bad to me, but I'm fine with using this to clean that up.
