### ISSUE TITLE
Error ABI encoding a number when setting spawn proxy

### ISSUE THREAD

**Issue by shrugs** [urbit/bridge#162]
Using the default mnemonic and attempting to set the spawn proxy for `~wicdev-wisryt` to `0xc617d51e3a1f621da8ae67b2f652d6ac02eb8d95`, I get `Error: invalid number value (arg="_prefix", coderType="uint16", value=65792, version=4.0.27)` as part of the `SpawnProxy#createUnsignedTx` function.

@Fang- any ideas?

**Comment by Fang-** [comment]
Planets can't have spawn proxies set because there's nothing for them to spawn. That action shouldn't be enabled in your case! (Try management proxy instead.)

**Comment by shrugs** [comment]
makes sense! looks like the logic [here](https://github.com/urbit/bridge/blob/mino/src/bridge/views/Point/Actions.js#L31) needs to be updated somehow, then

**Comment by Fang-** [comment]
Fixed in #165.
