### ISSUE TITLE
web3js#1490 was fixed, update SetKeys

### ISSUE THREAD

**Issue by shrugs** [urbit/bridge#163]
https://github.com/ethereum/web3.js/issues/1490

https://github.com/urbit/bridge/blob/mino/src/bridge/views/SetKeys.js#L63

**Comment by Fang-** [comment]
Fixed in latest mino. https://github.com/urbit/bridge/blob/5ca110db18133c5aca520f5f3fd8dfbd6c1a04aa/src/views/Admin/AdminNetworkingKeys.js#L99
