### ISSUE TITLE
on mobile, points page throws an error

### ISSUE THREAD

**Issue by jyng** [urbit/bridge#175]
I have a feeling this is being worked on, but wanted to log the error just in case. It works on desktop, but not mobile.
![IMG_3852](https://user-images.githubusercontent.com/9557907/60059981-924f0a80-96a3-11e9-9b3c-b2f7d9567caf.PNG)

Latest version of Chrome Mobile.

**Comment by jyng** [comment]
I logged in with the mnemonic provided in the README

**Comment by shrugs** [comment]
@jyng which branch are you building off of?

**Comment by jyng** [comment]
this is off of the mino branch
