### ISSUE TITLE
Request: display LinearStarRelease information within Bridge

### ISSUE THREAD

**Issue by jkmallard** [urbit/bridge#19]
Addresses who own points that are locked by the LinearStarRelease contract should see the time remaining and other info from the LinearStarRelease batch() function on their main Points page, and possibly also on the individual point pages as applicable.

It's non-obvious info to new users but also very relevant, and shouldn't be overly difficult to surface.

I'm willing to take a crack at this if it's considered a good idea and there's some consensus about where it should be displayed.

**Comment by Fang-** [comment]
Supporting the lockup contracts is highest on our new-features list for the next iteration of Bridge! I don't think we have an ETA yet (@gavinpatkinson, @jtobin ?), but we'll try to do frequent updates as the tool grows.

**Comment by vvisigoth** [comment]
Just reviewed the designs of this.
