### ISSUE TITLE
Please consider a less restrictive license.

### ISSUE THREAD

**Issue by abliss** [urbit/bridge#2]
The EULA is extremely onerous.

**Comment by robmyers** [comment]
Agreed. The no-reverse engineering and other clauses are at odds with our ownership of our Urbits.

If you want to cover your backs in terms of absence of warranties etc. more obviously than your usual MIT license appears to, I think the GPL will do that.

Or as an alternative I'd take a MIT-licensed command-line tool that prints a strongly-worded disclaimer each time it runs. I'd even write it if not for the EULA...

**Comment by eriknewton** [comment]
Thanks, guys. Absolutely agreed. I'll get a new set of license agreements out ASAP.

**Comment by eriknewton** [comment]
MIT it shall be. Updates imminent.

**Comment by iamwillkim** [comment]
Licensed under MIT License and removed EULA
