### ISSUE TITLE
It should not be possible to attempt to spawn a planet from a galaxy

### ISSUE THREAD

**Issue by jkmallard** [urbit/bridge#20]
Right now if you choose to spawn a planet with a galaxy parent, the Bridge tool will allow you to sign the transaction and send it.

Example: 
Galaxy ~zod is 0x0. 
Planet  ~dapnep-ronmyl is 0x10000. 
Ecliptic.getPrefix(~dapnep-ronmyl) will returns 0x0, or ~zod. 
~zod is the parent of ~dapnep-ronmyl. 

If you owned ~zod, you could use Bridge and attempt to spawn ~dapnep-ronmyl.
However a check in the ecliptic.spawn() function will always make this fail when it executes and you'll just waste gas. Apparently these planets are reserved/unavailable.

Bridge should not allow this transaction to be signed and sent.

**Comment by juped** [comment]
See also urbit/azimuth#7 regarding their eventual availability

**Comment by juped** [comment]
Yeah, it should be prevented in bridge until it's valid

**Comment by gavinpatkinson** [comment]
Yeah, we need better validation for this.

**Comment by jtobin** [comment]
Resolved by #22.
