### ISSUE TITLE
Confusing style of homepage on iOS (2.0.0beta)

### ISSUE THREAD

**Issue by loganallenc** [urbit/bridge#211]
On the homepage of Bridge, the “Offline” and “Activate buttons are below the fold on an iPhone X. (Not visible until you scroll down.) This feels like a UX problem to me for mobile users trying to activate a point. Thoughts?

**Comment by Fang-** [comment]
Invite emails will have a link that brings you straight to the activation page, clicking "activate" on the login screen should be a fairly really uncommon flow.

**Comment by shrugs** [comment]
an alternative is `position: fixed` floating footer, but that would take up unnecessary height, imo. I'd agree that the current behavior is a-ok.

**Comment by jyng** [comment]
The way I've solved this in the past is to use ```vh``` so that it always the same ratio of the screen height

**Comment by shrugs** [comment]
the existing app is already `vh`'d and the footer will always be at-or-below the fold, according to our spec. logan is pointing out that there's so much content on the login page that activate gets pushed below the fold and can't be found.

in any case this is 1) according to spec and 2) almost definitely the right solution (see the comments above) — closing as wontfix
