### ISSUE TITLE
Test wallet PNGs on a computer without fonts

### ISSUE THREAD

**Issue by g-a-v-i-n** [urbit/bridge#214]
PaperCollateralRenderer gets its fonts from the application it is imported into. The current version of PaperCollateralRenderer assumes Work Sans, Source Code Pro and SF Pro are available. The new Bridge uses Inter and Source Code Pro only.

To make this more complicated, the browser will source fonts that it needs but are not present in the application from the user's font collection.

We need to test what the current output of PaperCollateralRenderer is right now, on a machine that does not have Work Sans, Source Code Pro and SF Pro. This means using a Windows or Linux machine, as the SF system font is always available on MacOS.

I need to see the PNGs for wallets generated on a Linux or Windows machine. The legibility of the paper wallets is critically important.

If the wallets render in Times New Roman, this indicates that fonts are missing. The quick fix is to just include the missing fonts in CSS font-family.

The better fix is to regenerate the wallet template JSON, which is what I am doing now.

**Comment by Fang-** [comment]
Technical Q:

> PaperCollateralRenderer gets its fonts from the application it is imported into.

Meaning, it depends on either the system or the local CSS having those fonts available, and it cannot include those fonts itself because rendering only happens in HTML?

I can test this, sure. `rc-immediate` right?

**Comment by Fang-** [comment]
Well, I learned the wallet download doesn't work on Windows rn. Progress!

fwiw, my MacOS machine doesn't have SF Pro (but does have the other fonts manually installed), and paper renders like so:

![image](https://user-images.githubusercontent.com/3829764/62088989-81c41e00-b267-11e9-925f-ad1210c62e0a.png)

**Comment by vvisigoth** [comment]
we bundled 'em.
