### ISSUE TITLE
Ethereum Private key

### ISSUE THREAD

**Issue by rmariani** [urbit/bridge#229]
I was walking a user through the process of getting their key-file on [hosted Bridge](https://bridge.azimuth.network). They tried the "Ethereum Private Key" option under the "Advanced" tab. 

Their private key did not begin with `0x` -- [no Ethereum private key does](https://theethereum.wiki/w/index.php/Accounts,_Addresses,_Public_And_Private_Keys,_And_Tokens#Private_Key) -- which led to confusion, since example key in the field did begin in such a way. Anyways, the user copied their private key into the field, and it did not work. They received this message: 

```
Must be exactly 66 characters.
```

This is strange, since Ethereum private keys are 64 characters. Hosted Bridge only worked when the user prepended an `0x` to their private key, making it 66 characters. 

However, this requirement was absent from local Bridge. They could use their 64-character key (without `0x`) on that version, and I believe that hosted Bridge should work in this way.

**Comment by shrugs** [comment]
Ah, didn't realize private keys weren't always (or at all?) string-encoded hex. For context, mycrypto will display private keys like that, which is what i'd based that validation on (although it does strip 0x when logging in with a private key, so perhaps they realize that as well).

<img width="668" alt="image" src="https://user-images.githubusercontent.com/1535001/63022226-bad4d300-bea2-11e9-998b-832c5e437ec8.png">

(that's the bridge test account, so no stress on private key leaks)

Will solve this as part of #221!

In the meantime, `0x3a1076bf45ab87712ad64ccb3b10217737f7faacbf2872e88fdd9a537d8fe266` and `3a1076bf45ab87712ad64ccb3b10217737f7faacbf2872e88fdd9a537d8fe266` are equivalent in terms of the private key they represent, so the user could log in by prepending 0x to their private key

**Comment by Fang-** [comment]
Hex inputs in general are kinda messed up rn. On `AdminNetworkingKeys`, it takes hex strings starting both with and without `0x`, as long as the total string is of the expected length. On private key login, trying to do it without just crashes.

**Comment by shrugs** [comment]
ah, I guess our hex format validator accepts with or without the 0x prefix? and I'm not surprised it crashes, since all of the lib functions will strictly expect the right format.

we probably want to have inputs that enforce the 0x prefix using a parse/format hook like `prependSig` and then have the error message more 'accurate' by saying '64 hex characters' instead of '66 character', which is definitely confusing.

**Comment by Fang-** [comment]
It actually shouldn't, as far as the code is concerned?

https://github.com/urbit/bridge/blob/58b9f253fb3bd4f55f7d8a3acf7ec8a8cc221bd2/src/lib/validators.js#L18

But I agree that we want formatters to auto-prefix this for hex inputs, and then transformers to throw it away again if/where needed.
