### ISSUE TITLE
Block from web3 request can be null?

### ISSUE THREAD

**Issue by Fang-** [urbit/bridge#241]
Got this after getting forwarded to the home page, while testing invite flow on ropsten:

<img width="524" alt="image" src="https://user-images.githubusercontent.com/3829764/63523311-36b1c980-c4fa-11e9-8bb3-52eeb68a08ae.png">

Maybe we were asking for a block that was just a little bit too recent? This worked fine upon relogging.

**Comment by shrugs** [comment]
typescript would have been nice here 😅

**Comment by shrugs** [comment]
`blockNumber` is null because the transaction is still pending

> blockNumber - Number: The block number where this log was created in. null when still pending.

which when passed to getBlock gives us null as a response (imo it should throw, but _whatever_ web3.js)
