### ISSUE TITLE
Need to be able to signal breaches while setting networking keys

### ISSUE THREAD

**Issue by philipcmonk** [urbit/bridge#25]
When you set new networking keys, there's an argument called "discontinuous", which should be set if you're creating a new pier, so all your old connection state is gone.  Currently, we default this to false, but we should add a checkbox for it.

Arguably, we should default it to true since most of the time if someone's changing their keys it's because they're breaching their ship.  Counter-argument is that a breach is irreversible, while if you forget to set it you can just cycle the keys again with it set.

Not sure what's the best description for the checkbox that isn't Urbit-specific, but I suggest the following text:

- [ ] This is a discontinuous breach.  This should be set if you're going to clear network state.

**Comment by alexmatz** [comment]
@Fang- What do you think of this text? 
My ship sunk. This is a discontinuous breach. This should be set if you're going to clear network state. (it is irreversible)

**Comment by Fang-** [comment]
"Discontinuous breach" is redundant. (:

Depending on what angle we want to go with here:

- [ ] I have lost important off-chain data relating to this point and need to do a hard-reset.

- [ ] I am breaking continuity. For example, re-creating an Arvo ship.

**Comment by alexmatz** [comment]
@Fang- maybe we combine and do: I've lost important off-chain data relating to this point and need to do a hard-reset. For example, re-creating an Arvo ship.
