### ISSUE TITLE
Failing to convert decimals to BN

### ISSUE THREAD

**Issue by langalisc** [urbit/bridge#259]
Interface won't accept email address.  Note:  Email address used in this case had a dot before the @ symbol. 

> Error: [number-to-bn] while converting number 3.3 to BN.js instance, error: invalid number value. Value must be an integer, hex string, BN or BigNumber instance. Note, decimals are not supported. Given value: "3.3"

<img width="600" alt="Screen Shot 2019-08-27 at 9 24 04 AM" src="https://user-images.githubusercontent.com/30407155/63789601-8bfc2b00-c8ac-11e9-9c8d-958ec69f1d1f.png">

**Comment by Fang-** [comment]
Seems like this is not related to the email address, but rather internal logic that's messing up.

Looks like EthGasStation's API has started including decimals in its API all of a sudden. Will get this patched soon!

**Comment by Fang-** [comment]
Closed in #260. Will push out a new release later today!
