### ISSUE TITLE
Infinitely waiting on funds to send invite

### ISSUE THREAD

**Issue by loganallenc** [urbit/bridge#262]
![Screen Shot 2019-08-28 at 1 06 00 PM](https://user-images.githubusercontent.com/1377557/63888893-b1fcfa80-c994-11e9-945f-ec8966ce4a9e.png)

**Comment by Fang-** [comment]
Any console output? How long is "infinite"?

**Comment by vvisigoth** [comment]
cc @loganallenc ?

**Comment by alexmatz** [comment]
@loganallenc where is the stack trace, mark is out tomorrow, want him to get on this!

**Comment by alexmatz** [comment]
i think we solved this with Anthony's help yesterday. going to close this but please let him know if you encounter it again @loganallenc!
