### ISSUE TITLE
Inviting is broken, generates but won't send

### ISSUE THREAD

**Issue by alexmatz** [urbit/bridge#270]
![Screen Shot 2019-09-03 at 2 44 03 PM](https://user-images.githubusercontent.com/44714137/64210956-80cf6f00-ce59-11e9-901d-b4e0accbb70c.png)

**Comment by alexmatz** [comment]
the entire screen turns white after generating the invite and hitting send.

**Comment by vvisigoth** [comment]
@Fang- doesn't this look like what @jyng was running into on the testnet?

**Comment by vvisigoth** [comment]
I tried this and couldnt replicate on tmp

**Comment by vvisigoth** [comment]
closing because restarting fixes for some dumb reason.

**Comment by alexmatz** [comment]
@vvisigoth seems to have figured this out! going to close this.
