### ISSUE TITLE
How do I generate master tickets on Ganache?

### ISSUE THREAD

**Issue by vvisigoth** [urbit/bridge#272]
I would like to generate ship/master-ticket pairs for testing purposes (Paper wallet DL) and mnemonic login doesn't work for these purposes. Is there a simple way to do this using, say key-gen.js?

cc @Fang- @shrugs @jtobin

**Comment by jtobin** [comment]
On Wed, Sep 04, 2019 at 05:41:46PM -0700, Anthony Arroyo wrote:
> I would like to generate ship/master-ticket pairs for testing purposes
> (Paper wallet DL) and mnemonic login doesn't work for these purposes.
> Is there a simple way to do this using, say key-gen.js?

Yup, 'generateWallet' in urbit-key-generation will do the trick.  E.g.:

  const kg = require('urbit-key-generation')
  const wallet = await kg.generateWallet({ ship: '~zod', ticket: '~dozzod-dozzod' })

**Comment by vvisigoth** [comment]
thanks.
—
~poldec-tonteg
http://urbit.org
