### ISSUE TITLE
User should be able to specify network in offline mode

### ISSUE THREAD

**Issue by iamwillkim** [urbit/bridge#28]

**Comment by jtobin** [comment]
Bridge presently defaults to mainnet (i.e. uses a `chainId` of 1) when generating transactions in offline mode.  Users should really be able to specify their network of choice (Ropsten, local, etc.) here.

**Comment by c-johnson** [comment]
Has this been implemented with custom chainIDs in statelessTransaction, or is this referring to something else?

**Comment by jtobin** [comment]
@c-johnson Yup, it has.  I'll take the liberty of closing this one.
