### ISSUE TITLE
Bridge Crashing when Accepting Point

### ISSUE THREAD

**Issue by bioy-casares** [urbit/bridge#291]
Attempt to accept incoming point transfer yields a blank screen and the following error messages:
<img width="1440" alt="Screen Shot 2019-09-25 at 12 48 48 PM" src="https://user-images.githubusercontent.com/55156412/65634418-047d0700-df93-11e9-8969-1cb3cd51facc.png">

**Comment by vvisigoth** [comment]
Interesting. This error means that you went over the limit that the gas tank funds. We have an issue to improve this error handling.

Out of curiosity, were you doing a lot of transactions with this point? If so, how many?

**Comment by Fang-** [comment]
Regardless of anything else, that error in `fromWei` should certainly be fixed, and is another tick in the "typescript pls" column. I feel like I've fixed that particular error five times already.

**Comment by bioy-casares** [comment]
@vvisigoth I was not trying to do many transactions to this point, unless failed attempts count.  It's likely that I attempted to accept this point several times before copying the error messages.   Indeed, for other planets, sometimes after numerous attempts, the accept would succeed.

**Comment by reitraced** [comment]
i had this issue claiming a point
the problem that i found was that the default gas price was 8 gwei and the option to change it was hidden unless you clicked on advanced settings

**Comment by vvisigoth** [comment]
@Fang- This appears to happen on point accept when we dont' ahve enough gas. Should the gas-tank be activated in this case?

**Comment by reitraced** [comment]
i think that would be a good solution

-------- Original Message --------

**Comment by Fang-** [comment]
Yes, Bridge should (and apparently indeed will) attempt to use the gas tank in that case. But I'm inferring that it's hitting a `fromWei` error there consistently, for whatever reason. Can look into this.

A little bit confused by @reitraced's description of the issue. Default gas price should always be sane. If you set it lower, and your address already had a small amount of funds, then you might've just able to pay for it with a lower fee.

**Comment by reitraced** [comment]
yeah im new to this stuff
i was told to make a comment on this by people in urbit-help

-------- Original Message --------

**Comment by Fang-** [comment]
Closed via #302.
