### ISSUE TITLE
Reticket failing on Metamask/Trezor/Bridge

### ISSUE THREAD

**Issue by liam-fitzgerald** [urbit/bridge#293]
Reticket doesn't work when we don't have control of the private key. In addition, we need to batch the transactions so the user isn't inundated with requests.

**Comment by Fang-** [comment]
> Reticket doesn't work when we don't have control of the private key.

Is this because the flow is just poorly/inflexibly programmed? (ie assumes we're in a master-ticket-login situation)

**Comment by liam-fitzgerald** [comment]
Yeah it assumes we have a private key and can sign transactions in browser, as opposed to delegating the signing elsewhere (metamask, Trezor, etc.)

**Comment by Fang-** [comment]
It seems that neither [Trezor](https://github.com/trezor/connect/blob/develop/docs/methods/ethereumSignTransaction.md) nor [Ledger](https://github.com/LedgerHQ/ledgerjs/tree/master/packages/hw-app-eth) support batch-signing transactions.

**Comment by Fang-** [comment]
Fixed in #371.
