### ISSUE TITLE
How to use https in development

### ISSUE THREAD

**Issue by vvisigoth** [urbit/bridge#298]
https is true when I run pilot, but I still can't get a secure connection. Do I have to make a cert? If so, where do I put it?

**Comment by Fang-** [comment]
> I still can't get a secure connection

As in, https doesn't load, or it loads but browser says cert isn't sane? If the latter, what problems is it giving you?

Maybe [this](https://github.com/urbit/bridge/blob/master/README.md#https) is relevant. There's instructions for https outside of `pilot` [here](https://github.com/urbit/bridge/blob/master/README.md#run-bridge-with-ledger-support), but of course loses you all of `pilot`'s niceties...

**Comment by vvisigoth** [comment]
<img width="943" alt="Screenshot 2019-10-08 14 41 28" src="https://user-images.githubusercontent.com/1609955/66435467-c263b480-e9d9-11e9-9075-dbcd91cf05c4.png">

I get this.

The issue here is I'm trying to take screenshots for docs and I'd prefer to have a browser window...

**Comment by Fang-** [comment]
I... can't tell if that's `http://localhost:3002` or `https://localhost:3002`. Pls clarify.

A stupid workaround for this could be to type the most display-friendly URL into the address bar, but not hit return, and leave it there. Pretty sure that hides the warning. (^:

**Comment by vvisigoth** [comment]
I typed in https
—
~poldec-tonteg
http://urbit.org

**Comment by vvisigoth** [comment]
Also, changing the address and not entering, makes the exclamation pt _not
red_ but doesn't get rid of it.

mai lyfe
—
~poldec-tonteg
http://urbit.org
