### ISSUE TITLE
No optional passphrase field for mnemonic login

### ISSUE THREAD

**Issue by Fang-** [urbit/bridge#3]
There are cases where users have a mnemonic wallet that's additionally secured with a passphrase. `keygen-js` supports this, we just need to get the input fields in.

**Comment by gavinpatkinson** [comment]
I implemented the input field for this, I can handle this if @jtobin can point me in the right direction about walletFromMnemonic() in lib/wallet.

**Comment by jtobin** [comment]
(Following up in that PR).

**Comment by urbitalex** [comment]
@Fang- what is the status of this?

**Comment by jtobin** [comment]
@urbitalex I think this one just sort of stagnated.  It's partially implemented in #10, but there is some other stuff in there that has held it up.  The feature is not very difficult, though -- might be better to just code it up and merge it separately.

**Comment by alexmatz** [comment]
@jtobin thanks! I think so too!
