### ISSUE TITLE
Bridge email invite crashing

### ISSUE THREAD

**Issue by bioy-casares** [urbit/bridge#301]
Clicking "Generate invite" button on email invite page is causing page to crash.  
No error message on Chrome but page become unresponsive. 
Can't 'Inspect Element' to find an error on Safari because it goes immediately to spinning rainbow wheel. 
In both cases, the webpage starts consuming a lot of CPU.

**Comment by vvisigoth** [comment]
This was fixed with a restart, but it looks like the email service was crashing on the "did the email send already check."

**Comment by Fang-** [comment]
@vvisigoth do we have a stack trace or something? It shouldn't be crashing there (and that shouldn't kill the client).

**Comment by vvisigoth** [comment]
I didn't catch it at first, but it looked like it was an CERTIFICATE_ERR
from onboarding email service.
—
~poldec-tonteg
http://urbit.org
