### ISSUE TITLE
getting a 404 on use of bridge

### ISSUE THREAD

**Issue by joshuareagan** [urbit/bridge#31]
I tried to use bridge, but got 404ed:

```
~/Downloads/bridge-1.1.0$ python3.7 -m http.server 5000 --bind 127.0.0.1 --directory build
Serving HTTP on 127.0.0.1 port 5000 (http://127.0.0.1:5000/) ...
127.0.0.1 - - [02/Feb/2019 22:36:48] code 404, message File not found
127.0.0.1 - - [02/Feb/2019 22:36:48] "GET / HTTP/1.1" 404 -
```

**Comment by joshuareagan** [comment]
The problem is that the command in question must be run in the /src directory -- please consider revising the instructions to make that clearer

**Comment by joshuareagan** [comment]
to be clear it works now!

**Comment by iamwillkim** [comment]
Hey Josh, I'm not able to reproduce this. Are you running the command within the extracted zip file? There is not /src directory in this zip file, so I'm wondering if you are building from source as opposed to just using the pre-built release folder.

**Comment by joshuareagan** [comment]
Yes, I think that must be it.  Sorry!

**Comment by jtobin** [comment]
I've added some commentary to the README in #34 that should steer people away from building from source.  It totally wasn't clear before, unless one happened to land directly on the releases page.
