### ISSUE TITLE
Error Report: Please pass numbers as strings or BigNumber objects to avoid precision errors.

### ISSUE THREAD

**Issue by c-johnson** [urbit/bridge#310]
## Context

Trying to issue a planet from my star, ~lordef

~lordef

## Error

```
Error: Please pass numbers as strings or BigNumber objects to avoid precision errors.
    at fromWei (https://bridge.urbit.org/static/js/2.d800b7cb.chunk.js:1:140998)
    at kn (https://bridge.urbit.org/static/js/main.d93cb87c.chunk.js:1:123676)
    at Na (https://bridge.urbit.org/static/js/2.d800b7cb.chunk.js:1:1561481)
    at Go (https://bridge.urbit.org/static/js/2.d800b7cb.chunk.js:1:1604573)
    at Fo (https://bridge.urbit.org/static/js/2.d800b7cb.chunk.js:1:1590296)
    at qo (https://bridge.urbit.org/static/js/2.d800b7cb.chunk.js:1:1587316)
    at Lo (https://bridge.urbit.org/static/js/2.d800b7cb.chunk.js:1:1585876)
    at https://bridge.urbit.org/static/js/2.d800b7cb.chunk.js:1:1547777
    at t.unstable_runWithPriority (https://bridge.urbit.org/static/js/2.d800b7cb.chunk.js:1:1622220)
    at pi (https://bridge.urbit.org/static/js/2.d800b7cb.chunk.js:1:1547506)
```

**Comment by c-johnson** [comment]
Looks potentially like a duplicate of https://github.com/urbit/bridge/issues/306, so feel free to close.

Only other context; I was issuing a child planet (~somepl-anettt) to ~lordef's public key itself, and I have no ethereum in my ~lordef wallet. So potentially just a gas tank issue in my case.

**Comment by Fang-** [comment]
I was going to ask you to report the version number of your Bridge, to make sure you don't have an older version cached, but apparently we don't display that anymore? @vvisigoth what happened? (Though, I guess we should just include it in the error report.)

If you don't have enough funds, Bridge was likely trying to ask you to provide those, but then crashed trying to render the required amount. Should have been fixed in #302, if that's what you hit, but apparently not? Continues to be strange...

**Comment by c-johnson** [comment]
Could be a caching issue, yeah. I'll try again with a hard refresh and see if it does anything.

Cachebust all your assets! Should just be a simple Webpack tweak, right? :D :D :P jk jk sorry

**Comment by c-johnson** [comment]
Update again:

I sent some ethereum to the fresh receiving address (which now has $0.20 USD worth of ethereum, .0012 eth in it currently) 

I get the following javascript issue indicating that it is indeed a gas tank issue, which is weird, because I shouldn't need the gas tank, right?:

![image](https://user-images.githubusercontent.com/583272/67778105-b85d3080-fa30-11e9-87b2-c208bbbbb592.png)

**Comment by Fang-** [comment]
Thanks for the details @c-johnson, this is super helpful!

> Recovery issue.
This is precisely the repro I was waiting for. The gas tank indicates that the transaction that caused this was `0x0`. That is, not really a transaction at all! Knowing that, we'll have to look into why Bridge would ever send a `0x0` transaction.

It might still hit the gas tank in your case if the transaction's gonna be expensive. (`0.0012` isn't _that_ much eth.) It would've told you the required price but, you know, `fromWei`.

**Comment by c-johnson** [comment]
Funny enough, I think I lost the private key associated with the small amount of eth you gave me yesterday. 

Did I mention I hate crypto? I hate crypto.

**Comment by c-johnson** [comment]
Yep! Turns out it was a balance issue. I transferred another $5 USD worth of ethereum to the receiving account and it worked as expected. 

The fee was like $1.43 USD, which seems a bit high, but I'm just happy I got a transfer through, lol.

Now to connect this to OpenSea...

**Comment by Fang-** [comment]
I can't see any recent transaction with a fee that big. Can you paste the transaction hash, Etherscan link, or just the address you made the transaction with? Want to investigate just in case the fee is indeed abnormal.

**Comment by c-johnson** [comment]
Both of these: 

https://etherscan.io/tx/0xd5de3652e00b4eb8559fc7ba70b74bb21744c054a930cd89a1e332575fb9c010

https://etherscan.io/tx/0xd741eae2d58b65eb7e9a91bd0494766f00ba80d44f44c72a0a8093e43fe1d87d

They're both showing lower amounts than I transferred; both of them were around $1.45 in the metamask transaction before I confirmed it. Prices fluctuate of course, metamask might be out of date.

**Comment by Fang-** [comment]
Oh, I get it. Metamask was showing you the maximum amount you'd be paying, aka `gas-price * gas-limit`. In most cases you'll use less than the limit's worth of gas, so you pay less than the maximum you needed to ensure you had. These transactions seem sane to me (though the gas limit looks like it doesn't come from `constants.js`...)

**Comment by c-johnson** [comment]
Oh, okay. That makes sense! Thank you.

**Comment by Fang-** [comment]
Closing, as #321 was deployed and should have fixed this.
