### ISSUE TITLE
Instructions should be distributed with the release

### ISSUE THREAD

**Issue by msutherl** [urbit/bridge#33]
The release folder does not contain instructions for running the software. It's another thing to keep updated, but seems advisable!

**Comment by msutherl** [comment]
@jtobin should we revisit this?

**Comment by Fang-** [comment]
This seems completely fair. New release Soon™, I'll put this in with it.

**Comment by msutherl** [comment]
@Fang- some additional detail: working with a user currently who may be running the standard instructions on the release page and the `mkcert` instructions in the README simultaneously. I'd suggest presenting both of these sets of instructions in the same place and making it clear that it's an either/or choice.

**Comment by Fang-** [comment]
Resolved by putting instructions in the readme. #117 should take care of the rest.
