### ISSUE TITLE
suggested feature: ability to add a custom message with planet invite

### ISSUE THREAD

**Issue by rmariani** [urbit/bridge#338]
This would be very useful for tasks where there is a community-specific onboarding action, like with Hoon School. (Join these channels, etc)

**Comment by vvisigoth** [comment]
This is sa great idea
—
~poldec-tonteg
http://urbit.org

**Comment by Fang-** [comment]
This isn't hard to add. Should I implement, @vvisigoth?

**Comment by vvisigoth** [comment]
Yes, plz.
—
~poldec-tonteg
http://urbit.org

**Comment by galenwp** [comment]
I support this. 

One way this can often be confusing is that the person sending the message doesn't know how their message will be included in the email. I think we should either give the sender a preview of the email being sent, and make it clear what they're editing. Or just make the copy somehow get across that whatever they enter is going to be sent with a preface like 'A message from the person who invited you' or something.

**Comment by vvisigoth** [comment]
this is done already.
—
~poldec-tonteg
http://urbit.org
