### ISSUE TITLE
After personal breach, keyfile downloaded is old

### ISSUE THREAD

**Issue by vvisigoth** [urbit/bridge#346]
I did a personal breach (from  3 --> 4) and immediately DL'ed the keyfile. Keyfile was life 3.

Went back to family view, renavigated to the keyfile page and it DL'ed the correct one.

**Comment by Fang-** [comment]
Hmm, cannot reproduce. Immediately downloading the keyfile on-rekey always gives me a result consistent with future downloads. I'm assuming this was with a master ticket login? That's what I tried with, as most other methods give non-deterministic keyfiles, that aren't redownloadable. (Though they should be, within the same session... did we intentionally remove that?)

**Comment by galenwp** [comment]
Just experienced this. Not sure what I can offer in terms of repro — but exactly as described by vvisigoth.

**Comment by galenwp** [comment]
I wonder whether it can somehow be caused by ETH network congestion

**Comment by jtobin** [comment]
Encountering this again myself.

**Comment by matildepark** [comment]
Seems like this is the same issue as #137. Just noting ~

**Comment by Fang-** [comment]
Closing as duplicate of #137. See also the question there: anyone know of new cases of this since #423?
