### ISSUE TITLE
Reticketing using metamask broken

### ISSUE THREAD

**Issue by jyng** [urbit/bridge#353]
<img width="643" alt="Screen Shot 2019-12-10 at 12 29 28 PM" src="https://user-images.githubusercontent.com/9557907/70566364-c9798100-1b48-11ea-8136-f5dbdb9315f4.png">

This is in Admin > Reticket

**Comment by jyng** [comment]
<img width="804" alt="Screen Shot 2019-12-10 at 12 31 43 PM" src="https://user-images.githubusercontent.com/9557907/70566527-178e8480-1b49-11ea-8e03-cd398c9cba32.png">

**Comment by Fang-** [comment]
Was this logged in with metamask?

**Comment by jyng** [comment]
Correct

**Comment by vvisigoth** [comment]
Drat!
—
~poldec-tonteg
http://urbit.org

**Comment by shrugs** [comment]
confirmed: using the mnemonic from the same account is a workaround for the moment

**Comment by g-a-v-i-n** [comment]
also true for trezor, not sure why signin matters.

**Comment by Fang-** [comment]
Fixed in #371.
