### ISSUE TITLE
Rekeying networking keys

### ISSUE THREAD

**Issue by iamwillkim** [urbit/bridge#36]
We need to have a clear flow for allowing people who authenticate using the Urbit HD wallet to derive the next index networking seed in the case of compromised keyfile. 

Currently Urbit HD wallet users are expected to re-key using a random 32 byte hexadecimal string as opposed to having the Bridge tool derive the next networking seed (which is one of the benefits of using the HD wallet).

**Comment by Fang-** [comment]
Woah huh, I rekeyed ~paldev once and it pre-filled with the new derived revision-based networking seed. Does this not work anymore or something?

**Comment by jtobin** [comment]
> We need to have a clear flow for allowing people who authenticate using the Urbit HD wallet to derive the next index networking seed in the case of compromised keyfile.

This should actually be ok in current Bridge.  The network itself seed remains secret even in the event of keyfile loss, so users shouldn't need to generate a new one unless their management seed (or ticket + optional passphrase, if it exists) becomes compromised.

**Comment by jtobin** [comment]
Derp.  My TLDR should actually read: a single management seed is used to generate an arbitrary number of network seeds.  Apparently I've already forgotten the details of the work I did like a month ago..
