### ISSUE TITLE
Apparent routing error

### ISSUE THREAD

**Issue by jtobin** [urbit/bridge#361]
In v2.1.3 on bridge.urbit.org.  To reproduce:

1) Authenticate (with master ticket) as ~dozzod / ~dozzod.  Bridge will warn "This wallet is not the owner or transfer proxy for this point;" click "Login anyway."

2) Bridge will show "No points to display.  [..]"  Click "View a point" on the bottom of the page.

3) See:

![](https://dsh.re/13120)

**Comment by Fang-** [comment]
Huh, that's weird. This is resolved on master as per #358 though, which removes the "view a point" button entirely. I'll try to get a release in by end of day, hoping to get the remaining PRs reviewed.
