### ISSUE TITLE
Feature Request: Invite Email Reminder / Follow Up

### ISSUE THREAD

**Issue by bioy-casares** [urbit/bridge#362]
Bridge tells me I have sent 39 invites, of which 8 have been accepted.  Somewhat disappointing conversion rate, considering every invitee seemed very enthusiastic about Urbit. That suggests that of the 31 invitees who did not activate, most probably just missed the email / forgot about it. 

A feature that could improve this situation would be an automated follow-up email to remind those who receive planets (but don't activate them) to activate them.  For example, after 2 weeks / 1 month / 2 months of non-activation, a reminder email is sent out.  This assumes there are no technical barriers to knowing which invite corresponds with which email. 

<img width="632" alt="Screen Shot 2019-12-20 at 6 07 50 PM" src="https://user-images.githubusercontent.com/55156412/71299263-84c8c380-235a-11ea-9e0d-ed1c7f06cf3f.png">

**Comment by Fang-** [comment]
> This assumes there are no technical barriers to knowing which invite corresponds with which email.

Hmm. The email sender doesn't actually keep email addresses around, let alone associate them with specific invites... There's not so much a technical barrier there, as there is a legal one. Keeping email addresses around of users who didn't necessarily know it was gonna pass through our hands seems icky.

Maybe if we destroy that data after a 1-week reminder it's Less Bad, but I'm not a lawyer, so I really can't make this call. I'll ask around.

**Comment by Fang-** [comment]
Can confirm we don't want to keep emails around.

Worth noting that we also get plenty of reports from people saying the invite email went into their spambox. Perhaps that's a better place to start solving the problem.

Closing this as wont-fix, but thanks for the suggestion!
