### ISSUE TITLE
HD Path Derivation Confusion

### ISSUE THREAD

**Issue by tynes** [urbit/bridge#37]
I wanted to check to make sure that mycrypto would derive the same paths as bridge.  I am finding that they are not.  I am able to derive the same public key, but only when I use a depth of 1 less on Bridge compared to mycrypto. I also believe that Ethereum uses a depth of 4, the default shown is a depth of 5.

I don't want to post my public keys, so I will explain how to recreate.

- Go to https://mycrypto.com
- Attach a ledger device
- Let it derive keys from m/44'/60'/0'
- View first key, take note of it, it corresponds to m/44'/60'/0'
- Go to bridge, attach ledger device
- Use path m/44'/60'/0'
- Press Authenticate, take note of the key at the top of the page (its different for me)
- Now use path m/44'/60'/0'/0
- Now the key matches the one derived by mycrypto at m/44'/60'/0'

Can you recreate this or am I doing something wrong?

**Comment by tynes** [comment]
Digging into the code here: https://github.com/urbit/bridge/blob/master/src/views/Ledger.js#L48

Its definitely passing in the correct path. I think that this comes from a confusion on UX.
I was expecting mycrypto to derive each of the keys it shows starting at the current depth and increment by one each time. After playing with it a bit more, they start deriving keys at the next depth, starting at 0

**Comment by jtobin** [comment]
Right.  That arguably makes sense on mycrypto's end; if one is providing a list of addresses then it probably makes more sense to iterate over `0, 1, 2` at depth 5 than than the hardened addresses `0', 1', 2'` at depth 4.  But they could perhaps be more explicit about it.

I'll close this, in the meantime, as I don't think it's really a Bridge problem per se.  Feel free to reopen if you reckon I've left something unresolved, though.
