### ISSUE TITLE
Generate invite URL doesn't seem to work, nor does inviting

### ISSUE THREAD

**Issue by galenwp** [urbit/bridge#379]
After clicking 'Generate URL' Bridge seems to hang. I get the attached in the dev console.

<img width="912" alt="Screen Shot 2020-01-31 at 12 09 59 PM" src="https://user-images.githubusercontent.com/1467211/73571111-b6857d80-4422-11ea-8581-6567fe688462.png">

**Comment by galenwp** [comment]
Actually, I hit the same bug when trying to simply invite someone over email.

**Comment by galenwp** [comment]
(These look the same to me, but maybe I'm missing something — anyway here's a screenshot from trying to invite)

<img width="912" alt="Screen Shot 2020-01-31 at 12 16 25 PM" src="https://user-images.githubusercontent.com/1467211/73571523-9609f300-4423-11ea-9f0b-5bfa2eb10ae8.png">

**Comment by Fang-** [comment]
Can reproduce. Investigating!

**Comment by galenwp** [comment]
Thanks!

**Comment by Fang-** [comment]
Fixed in #380.

**Comment by galenwp** [comment]
Thanks!
