### ISSUE TITLE
Error message when trying to create network key/reticket using local Bridge

### ISSUE THREAD

**Issue by mosbuma** [urbit/bridge#386]
I am trying to create network keys using a locally installed bridge, but get 

![urbit-networkkeys-error](https://user-images.githubusercontent.com/4919958/73725615-0e2b2e00-472e-11ea-9909-62c417984bb3.png)

Seems like this happens with all operations that interact with Ethereum (create network keys, reticket). 

I am running Bridge bridge-2.3.1 on Ubuntu 16.0.4, using python 3.7.2

**Comment by mosbuma** [comment]
After building a local version from source (2.3.3) and connecting to the mainnet I was able to generate the network keys and also able to reticket the planet. Build version 2.3.3 still gives the same error.

**Comment by Fang-** [comment]
Huh, so this only happens with the version downloaded from the release page? Very curious, will investigate!

**Comment by mosbuma** [comment]
If there is something that I can test/do on my side: just let me know

**Comment by liam-fitzgerald** [comment]
potential dupe of #410

**Comment by Fang-** [comment]
Indeed. Closing as duplicate of #410.
