### ISSUE TITLE
Garbled master ticket when claiming an invite

### ISSUE THREAD

**Issue by bioy-casares** [urbit/bridge#393]
Downloaded passport.  Master ticket file was garbled.  See photo:
<img width="881" alt="Screen Shot 2020-02-07 at 7 59 53 PM" src="https://user-images.githubusercontent.com/55156412/74078871-8c185f00-49e4-11ea-90cf-a6c0159f579b.png">

**Comment by bioy-casares** [comment]
Opened the image with Preview on Mac

**Comment by galenwp** [comment]
What browser were you using?

**Comment by bioy-casares** [comment]
Safari Version 13.0.4    (15608.4.9.1.3)

**Comment by Fang-** [comment]
@g-a-v-i-n any thoughts on this?

**Comment by g-a-v-i-n** [comment]
@bioy-casares Can you give us more context? Do you have any MacOS or Safari accessibility settings turned on? Anything unusual that could be related?

**Comment by bioy-casares** [comment]
Hey everyone, 

This was a while ago on an old out-of-date computer.  As you mention, probably related to some settings issue.  I can't reproduce it right now.  If I get the issue again I'll document the settings configuration more thoroughly.
