### ISSUE TITLE
Transaction failed on dev environment while testing linear release

### ISSUE THREAD

**Issue by vvisigoth** [urbit/bridge#397]
![Bridge](https://user-images.githubusercontent.com/1609955/74891970-3a08ff00-533d-11ea-8957-ac4a65caa9e3.gif)

fails with this error in the console

<img width="670" alt="Screen Shot 2020-02-19 at 5 26 48 PM" src="https://user-images.githubusercontent.com/1609955/74891997-49884800-533d-11ea-958a-6066ef38b388.png">

@liam-fitzgerald

**Comment by liam-fitzgerald** [comment]
Weird, error trace means we're trying to do an invalid transaction on the EVM. Will try and repro

**Comment by liam-fitzgerald** [comment]
So it's erroring because the linear star release contract doesn't have as many stars deposited as it should, i.e. the contract promises 10 stars, but only 5 were actually deposited. Will rectify, but it shouldn't be urgent.
