### ISSUE TITLE
Failure to create galaxies on local environment

### ISSUE THREAD

**Issue by jyng** [urbit/bridge#398]
<img width="706" alt="Screen Shot 2020-02-20 at 12 47 39 PM" src="https://user-images.githubusercontent.com/9557907/74977243-35952280-53df-11ea-8629-c8f454457c08.png">

<img width="1436" alt="Screen Shot 2020-02-20 at 12 46 51 PM" src="https://user-images.githubusercontent.com/9557907/74977217-2910ca00-53df-11ea-8139-a9e9a202305a.png">

<img width="1014" alt="Screen Shot 2020-02-20 at 12 49 37 PM" src="https://user-images.githubusercontent.com/9557907/74977397-7c831800-53df-11ea-9d65-c4cd7ce98605.png">

**Comment by liam-fitzgerald** [comment]
Looks like your local ganache/truffle environment might've crashed. Can you confirm?

**Comment by liam-fitzgerald** [comment]
any local env issues have been closed by #429
