### ISSUE TITLE
Invite URLs should auto-copy to clipboard

### ISSUE THREAD

**Issue by Fang-** [urbit/bridge#417]
A user told me: "I generated a url then clicked somewhere else, now the url is gone"

Given that we want to minimize invite losses, might it make sense to automagically put these in the users' clipboard once they're generated? I know the copy button is on-screen already, but having it be "Copied", then revert to "Copy" on initial display doesn't seem too bad to me.

**Comment by Fang-** [comment]
Alternatively (additionally?) we could allow users to retrieve invite codes from the "pending" invites for those they created within the same session. UX there might be harder to get right though.

**Comment by lukestiles** [comment]
If we are going to automatically push this into the copy buffer there should be messaging describing what has happened.
