### ISSUE TITLE
Cannot download keyfile after configuring keys with MetaMask

### ISSUE THREAD

**Issue by aed22** [urbit/bridge#421]
It says 

> custom or nondeterministic networking keys cannot be re-downloaded.

also something that I think is connected to this is that I used metamask to login.
and it gave me the following when i tried to reset networking keys.

> WalletMiddleware - Invalid "from" address.

and another error from the console:
> inpage.js:1 Uncaught Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.
    at Object.<anonymous> (inpage.js:1)
    at Object.2../createStandardProvider (inpage.js:1)
    at i (inpage.js:1)
    at t (inpage.js:1)
    at inpage.js:1

**Comment by liam-fitzgerald** [comment]
are you using brave?

**Comment by aed22** [comment]
Yes

**Comment by liam-fitzgerald** [comment]
If you're using the Brave Wallet as well, then that's a known bug w/ [metamask](https://github.com/MetaMask/metamask-extension/issues/8012). In the meantime you can export your mnemoic from metamask and use that to log into bridge.

**Comment by aed22** [comment]
Got it working on chrome with the mnemonic

**Comment by lukebarnard1** [comment]
I'm getting the same message but I'm using Chrome + Metamask.

There's a message in my console that seems related: `seed is nondeterminable for revision 1`

For context, I'm trying to use https://bridge.urbit.org/ with a new urbit planet identity I bought, which is now in my metamask wallet.

**Comment by Fang-** [comment]
@liam-fitzgerald does the above apply in the Chrome + MetaMask case as well? Any thoughts on this?

**Comment by Fang-** [comment]
I suspect this was fixed in the [v2.5.4 release](https://github.com/urbit/bridge/releases/tag/v2.5.4), where we made keyfile derivation deterministic. Closing as such!

In most non-urbit-wallet cases though, keys set using prior Bridge versions will still not be derivable, meaning you'd have to rekey (and not forget to `|rekey` in your urbit) to get back into a "can always download keyfile" situation.
