### ISSUE TITLE
"null has no properties" in star release logic, on Points page

### ISSUE THREAD

**Issue by Fang-** [urbit/bridge#426]
Getting this in console all the time when loading the Points page, on master.  Maybe it needs to be tidier about handling the "have no lockup" case?

<img width="393" alt="image" src="https://user-images.githubusercontent.com/3829764/77464943-3b2fbf00-6e08-11ea-9bf7-f8f6a92b3e01.png">

**Comment by liam-fitzgerald** [comment]
Are you using npm run pilot? The deploy scripts in azimuth-solidity don't include the star release contracts. see the email i just sent you

**Comment by Fang-** [comment]
Yes, this was with the dev setup. Do these objects just fall to null if the associated address isn't in use? Huh. Maybe we can handle this more gracefully. It's a dev-setup-only thing, and a shitty-dev-setup one at that, but it's still noise you'll run into when trying to repro unrelated things...

**Comment by liam-fitzgerald** [comment]
I think we should just fix the dev setup
