### ISSUE TITLE
Can't log in with metamask on Brave

### ISSUE THREAD

**Issue by philipcmonk** [urbit/bridge#435]
Tried to log in with metamask on Brave like normal (haven't logged in this way in about a month), and it's saying "Metamask is not installed on this browser" with no errors in the console.

**Comment by liam-fitzgerald** [comment]
Do you have the Brave in-browser wallet setup? Can I also get the version of Brave & metamask?

**Comment by philipcmonk** [comment]
No, I haven't switched to the in-browser wallet yet.

Metamask: 7.7.8
Brave: Version 1.5.115 Chromium: 80.0.3987.149 (Official Build) (64-bit)

**Comment by liam-fitzgerald** [comment]
Can you ensure that `Web3 provider for using Dapps` is set to Metamask in `brave://settings`?

**Comment by philipcmonk** [comment]
Ah, you're correct.  I guess Brave force-changed it to Crypto Wallets.  When I switched it back to metamask it worked.  Thanks!
