### ISSUE TITLE
Valid email is considered invalid for invite group

### ISSUE THREAD

**Issue by rmariani** [urbit/bridge#438]
An `email.arizona.edu` address that I receive an email from is not considered a valid email by bridge.

**Comment by shrugs** [comment]
i checked the form validation email regex with regexpal and it was happy with `test@email.arizona.edu`, so perhaps the validation error is in the mailer service?

**Comment by Fang-** [comment]
Hm, weird. There's no email validation on the mailer service, it just naively tries sending to whatever target address was passed in (assuming other conditions are met).

**Comment by shrugs** [comment]
i am sufficiently confused then. @rmariani  without doxxing that email, can you give us more info about the format?

**Comment by liam-fitzgerald** [comment]
did you copy paste the email? I suspect it may unicode shenanigans

**Comment by rmariani** [comment]
I did copy-paste it. Let me try typing it manually.

**Comment by rmariani** [comment]
I copy-pasted it again and it suddenly worked.

**Comment by Fang-** [comment]
Might've included a newline or something accidentally? Closing as user-error unless something more definitive comes up.
