### ISSUE TITLE
no web3 contracts causes throw on login

### ISSUE THREAD

**Issue by shrugs** [urbit/bridge#440]
i've done a fresh install of bridge and run `npm run pilot`. logging in with the ganache mnemonic throws an error in Points.js about `c.value.ownedPoints is null`.

i tracked it down to https://github.com/urbit/bridge/blob/master/src/store/lib/useControlledPointsStore.js#L32 where `ownedPoints` must be set to null as a result of the web3 fetch.

which is probably because the contracts weren't deployed locally.

i'll deploy the contracts, but the app should probably handle that case in a special way

**Comment by lukestiles** [comment]
How does an end user get to this state?

**Comment by shrugs** [comment]
end user would never see this, since bridge.urbit would presumably always point to a valid set of contracts. but useful developer experience benefit imo, if this issue still exists, since it’s about 2 years old at this point. i/ admin can close if no longer relevant

**Comment by lukestiles** [comment]
Closing as it isn't ever seen by an end user.
