### ISSUE TITLE
UX Fix [Gray Activation Code Text]

### ISSUE THREAD

**Issue by kennyrowe** [urbit/bridge#443]
I've received a few reports that the activation code workflow is not intuitive. Typically we've been trained to ignore gray text and the prepopulated activation code is gray. I find people asking me "where's my activation code?" because they assume the text in the field is just filler text when it's actually their activation code.

I suggest hiding the input box altogether if the activation code is prepopulated and directing the user's attention to advancing to the next step in the process.

**Comment by matildepark** [comment]
Seems like it's from [this](https://github.com/urbit/bridge/blob/master/src/indigo-react/components/Input.js#L96), since we pre-fill the field without `touch`ing it. I wonder if it's possible to, as part of passing it as a prop from the route, pass the appropriate prop to make it black ...
