### ISSUE TITLE
Metamask popup appears on loading Bridge

### ISSUE THREAD

**Issue by Fang-** [urbit/bridge#456]
Whether it's the main login page, or the "accept an invite" page, loading it causes Metamask to show its popup asking me to input my password and log in.

I would expect this to only happen when trying to log in with Metamask, not on pageload. This wasn't happening prior to v2.4.0. Suspect it got introduced by #431. Can anything be done about this? It's a bit annoying. (But obviously also not the end of the world.)

**Comment by shawntobin** [comment]
Closing since this doesn't appear to be happening anymore.
