### ISSUE TITLE
Persistent transaction receipt polling

### ISSUE THREAD

**Issue by Fang-** [urbit/bridge#457]
Situation: I played around with Ropsten Bridge a little bit to test the latest release. Sent two invites, then looked at the networking tab in browser console for laughs. It was polling pretty aggressively, despite #454 being in. And there was seemingly no end to it, either. I observed for a minute or two, but it never stopped.

![post-invite](https://user-images.githubusercontent.com/3829764/81081314-08daac80-8ef2-11ea-875f-d0fb504918bd.gif)

Most of these requests seemed to be about the transaction receipt:

<img width="435" alt="image" src="https://user-images.githubusercontent.com/3829764/81081122-cd3fe280-8ef1-11ea-83f5-7045458b10e6.png">

But we shouldn't care about that after it's been confirmed... right? Maybe we should stop polling for it somehow after we've got the confirmation we wanted.

**Comment by lukestiles** [comment]
Closed as the invite flow is no longer supported.
