### ISSUE TITLE
Setting gas and Transaction ID when setting network seed

### ISSUE THREAD

**Issue by dentropy** [urbit/bridge#468]
I have recently bought urbit planet and I have been trying to set it up. I logged into the bridge using metamask to set a custom network seed. Seems like the gas price is set and can not be changed when sending the transaction. The transaction then takes 6 hours. When I used the speed up transaction within metamask the transaction hash changes therefore the urbit bridge does not see the transaction happen.

**Comment by Fang-** [comment]
I think most transaction screen allow you to "view details" or similar, where you can change the gas price. Not sure, but wouldn't expect that to be different for the Metamask case.

Either way, we've taken note of this issue, and have doubled the max suggested gas price in #467. I'll be pushing that live in a new Bridge version shortly. Closing as such. Sorry for the trouble!

> When I used the speed up transaction within metamask the transaction hash changes therefore the urbit bridge does not see the transaction happen.

Hmm yeah, Bridge would lose track of the transaction, and might need to be refreshed to take note of the successful key change.

**Comment by dentropy** [comment]
I was able to fix the problem by just feeding in my private key raw. Thanks for taking note of my issue
