### ISSUE TITLE
Error when trying to reset networking keys

### ISSUE THREAD

**Issue by Electr0phile** [urbit/bridge#470]
The following error always shows up when I choose to reset networking keys and press "Send transaction":

```
fromWei@https://bridge.urbit.live/static/js/2.08959844.chunk.js:1:69433
kn@https://bridge.urbit.live/static/js/main.d62493ab.chunk.js:1:123906
Na@https://bridge.urbit.live/static/js/2.08959844.chunk.js:1:1562005
Go@https://bridge.urbit.live/static/js/2.08959844.chunk.js:1:1605097
Fo@https://bridge.urbit.live/static/js/2.08959844.chunk.js:1:1590822
qo@https://bridge.urbit.live/static/js/2.08959844.chunk.js:1:1587840
$o@https://bridge.urbit.live/static/js/2.08959844.chunk.js:1:1586400
fr/<@https://bridge.urbit.live/static/js/2.08959844.chunk.js:1:1548301
t.unstable_runWithPriority@https://bridge.urbit.live/static/js/2.08959844.chunk.js:1:1622744
pr@https://bridge.urbit.live/static/js/2.08959844.chunk.js:1:1548030
fr@https://bridge.urbit.live/static/js/2.08959844.chunk.js:1:1548249
yr@https://bridge.urbit.live/static/js/2.08959844.chunk.js:1:1548182
Vo@https://bridge.urbit.live/static/js/2.08959844.chunk.js:1:1585391
Ga@https://bridge.urbit.live/static/js/2.08959844.chunk.js:1:1565140
e/</<@https://bridge.urbit.live/static/js/main.d62493ab.chunk.js:1:133751
c/<@https://bridge.urbit.live/static/js/main.d62493ab.chunk.js:1:23312
u@https://bridge.urbit.live/static/js/2.08959844.chunk.js:1:1763201
l/a._invoke</<@https://bridge.urbit.live/static/js/2.08959844.chunk.js:1:1762990
D/</e[t]@https://bridge.urbit.live/static/js/2.08959844.chunk.js:1:1763623
i@https://bridge.urbit.live/static/js/2.08959844.chunk.js:1:2259
o@https://bridge.urbit.live/static/js/2.08959844.chunk.js:1:2462

```
In Bridge version 2.1.3.

The broader context:

When I create comets and when I run my planet I can only reach my own star and my own galaxy with |hi, all other stars and galaxies fail, and when I try to connect to chats there is always an http 504 error.

I tried the silver bullet, did not help.

So I tried resetting network keys with a breach. But the transaction took too long, so I went to the pending transaction in Metamask menu and chose to speed it up by spending more ETH. When the transaction completed, bridge was still waiting for the transaction to finish. I waited for a while and just refreshed bridge. I guess that the breach was successful because "Last set" field in the networking menu updated successfully. However, now when I try to reset keys again it always shows the error at the beginning of this post.

**Comment by liam-fitzgerald** [comment]
hi @Electr0phile it appears that the version of Bridge hosted at urbit.live is out of date. Can you confirm if this still occurs on the latest version of bridge [here](bridge.urbit.org)

**Comment by Electr0phile** [comment]
It worked, thanks!
