### ISSUE TITLE
"insufficient funds" for gas * price + value

### ISSUE THREAD

**Issue by tacryt-socryp** [urbit/bridge#484]
Trying to withdraw stars from my contract and this functionality doesn't work and I don't know how to make it work. Please advise.

**Comment by Fang-** [comment]
@liam-fitzgerald does #482 fix this?

**Comment by liam-fitzgerald** [comment]
yes

**Comment by tacryt-socryp** [comment]
This is still an issue and I don't know how to withdraw my star from my contract because the functionality doesn't work.

**Comment by Fang-** [comment]
Well, do you have sufficient funds to pay for the transaction?

**Comment by tacryt-socryp** [comment]
I did not at the time, no. But I assumed it was an application error because of the way it was presented. Also, it’s unclear when and what qualifies you to use the gas tank!
