### ISSUE TITLE
"tx could not be decoded" when signing with Ledger

### ISSUE THREAD

**Issue by eglaysher** [urbit/bridge#490]
When attempting to set networking keys for ~littel-ponnys when using a Ledger which contains the management proxy, it fails with the following error:

```
Node error: {"code":-32602,"message":"transaction could not be decoded: could not RLP decode raw input: invalid hex input"}
```

But when I paste the following signed transaction into Etherscan's broadcaster, it works:

```
0xf9010a06850826299e00830186a0946ac07b7c4601b5ce11de8dfe6335b871c7c4dd4d80b8a44447e48c00000000000000000000000000000000000000000000000000000000a857c7ecd99b480565b3ff1c55d84448c23723cdc87a937f89a5abccfc69113f9bf63fa434225c9a2671aefa845c1d3521e9eb0facc216ac65f77f7f48ce0ccea92fc9f60000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000125a068263f6b549678ecc509001fdfe57e540db483fb406972e1fbdc3f78021d491ba06c44fb8b073f071bfb630f85547a2864c862f5d2eaf260698a5b8a544d0c1b0e
```

This is a problem since the keys appear to be derived, but after the transaction above posts and I reload, bridge claims they're custom keys. I'd set custom keys, but since I can't submit the transaction inside Bridge, I can't download the keyfile before shutting down bridge.

**Comment by Fang-** [comment]
> since I can't submit the transaction inside Bridge, I can't download the keyfile before shutting down bridge.

@liam-fitzgerald #431 enables us to do deterministic/retrievable keys even for non-custodial wallets. Did you have something for that in the pipeline, or is that not yet scheduled? (cc @vvisigoth)

**Comment by eglaysher** [comment]
FYI, I was able to work around this by using Metamask to talk to my Ledger.
