### ISSUE TITLE
Bridge displays "This invite code cannot be recovered" after clicking "show" on an invited planet

### ISSUE THREAD

**Issue by sivner-figbus** [urbit/bridge#492]
The planet was invited before Bridge had the option to re-display the invite code for a planet.

The invite code was not made visible at the time it was issued.

I have 3 open invite-by-URL invitations in my bridge - I see the same error for all 3 of them, although only 1 of them actually requires recovery.

This problem is the subject of an (as yet unanswered) email to support@urbit.org, which was sent before Bridge had the option to re-display invitation codes  - you may wish to delete the mail from the queue there if you answer this.

**Comment by Fang-** [comment]
> The planet was invited before Bridge had the option to re-display the invite code for a planet.

This functionality will, unfortunately, only work for invites created using Bridge v2.5.1 and onward. Retrieving older invites would require literally brute-forcing it. Sorry!

The star owner still has access to the planet in question, and can revoke/manually transfer it if they so desire, so it's not like the planet has been lost to the void, at least.

**Comment by sivner-figbus** [comment]
Thank you!
