### ISSUE TITLE
Node error: {"code":-32602,"message":"transaction could not be decoded: could not RLP decode raw input: invalid hex input"}

### ISSUE THREAD

**Issue by JohnELester** [urbit/bridge#494]
I created an invite pool for ~dasfeb and have been sending out planet invites.  

Other people have been successfully claiming their planets from the invites, but one person got this error during the process:

Node error: {"code":-32602,"message":"transaction could not be decoded:
could not RLP decode raw input: invalid hex input"}

Screenshot below:

![Screenshot_20200717_104500](https://user-images.githubusercontent.com/25461543/87809777-e9cd9480-c829-11ea-8b6d-80303af7534d.png)

**Comment by Fang-** [comment]
Thanks for filing! I just fixed this in #495, and have pushed that out as Bridge v2.5.3. They may need to cache refresh their browser to make sure they're running that latest version.

Closing, lmk if they have further trouble.
