### ISSUE TITLE
Sigil margins are inconsistent & incorrect

### ISSUE THREAD

**Issue by Fang-** [urbit/bridge#496]
Just observed this in v2.5.3. Did some npm wrangling prior to this, not sure what I kicked, but some sigils get rendered kinda poorly. Stars get weird margins in the passports and mini-passports, and sigils in input fields don't have any margin/padding at all.

<img width="491" alt="image" src="https://user-images.githubusercontent.com/3829764/87812613-c1ad5800-c860-11ea-98ae-283724789b5b.png">

<img width="248" alt="image" src="https://user-images.githubusercontent.com/3829764/87812510-94f94080-c860-11ea-9721-5854f0a6e60a.png">

**Comment by Fang-** [comment]
I solved the "no margins" problem in 059ed84, but still don't know what's up with the weird cutoff situation. @g-a-v-i-n any idea where the problem with this could be? The top level `<g>` in the svg has weird `right` and `bottom`(?) values, setting those to 0 fixes this:

![sigil-futz](https://user-images.githubusercontent.com/3829764/87818746-65036a80-c86b-11ea-8b0b-e289ad7000bf.gif)

**Comment by JohnELester** [comment]
I just noticed this with ~dasfeb.

![1](https://user-images.githubusercontent.com/25461543/87829722-94a37a00-c84d-11ea-8e98-e244195d2a59.png)

![2](https://user-images.githubusercontent.com/25461543/87829729-979e6a80-c84d-11ea-8f29-60637ca5a4d5.png)

**Comment by g-a-v-i-n** [comment]
looks like an issue with sigil-js, will take a look

**Comment by g-a-v-i-n** [comment]
you likely need to use the following in the config
```js
            width: size,
            height: size / 2,
            margin: false,
```

**Comment by Fang-** [comment]
@g-a-v-i-n that doesn't change the visual result here, and the values I noted are still there...

**Comment by g-a-v-i-n** [comment]
Would you kindly point me to a branch?

**Comment by Fang-** [comment]
master is fine, not much development is happening outside of that.

**Comment by g-a-v-i-n** [comment]
What do you mean by `right` and `bottom` values? Are you referring to CSS, style properties or something else? I'm having a hard time getting to the bottom of this because I don't know the Bridge codebase and sigils render as expected on the sigil-js test page.

**Comment by Fang-** [comment]
In the gif, you can see the outer `<g>` has a transform matrix of `0.5,0,0,0.5,-32,16`, which I think is "width, height, top, left, right, bottom"?

I'll email you with test account details for ropsten. If you're using `npm run pilot` instead of bridge-tmp.urbit.org, you'll want to change this to end in `.ROPSTEN;`

https://github.com/urbit/bridge/blob/7d185a94ee142e82d3e51492dd80adf52831a2a2/src/Bridge.js#L23

Sigil component lives here:

https://github.com/urbit/bridge/blob/7d185a94ee142e82d3e51492dd80adf52831a2a2/src/components/Sigil.js#L3-L13

**Comment by sigilante** [comment]
![image](https://user-images.githubusercontent.com/57601680/90838600-e347a680-e31a-11ea-9076-8b11990f698a.png)

Yeah, seeing this for stars.

**Comment by matildepark** [comment]
Tagging @tylershuster

**Comment by tylershuster** [comment]
oh hi mark
