### ISSUE TITLE
Visual bug: checkboxes are broken

### ISSUE THREAD

**Issue by ixv** [urbit/bridge#499]
On both the disclaimer page and the networking key page, clicking the checkbox doesn't put a checkmark in it. Seems to be a visual bug, since on the disclaimer page, clicking the checkbox still controls  the "continue" button.

![image](https://user-images.githubusercontent.com/4741759/87835101-07f2bf00-c841-11ea-9485-ab3d9b1490f3.png)

![image](https://user-images.githubusercontent.com/4741759/87835105-0cb77300-c841-11ea-9b8c-345bf972afd8.png)

Confirmed on brave, chrome, safari, and firefox.

**Comment by johnmendonca** [comment]
Seeing this also on all checkboxes on firefox and chromium linux.
