### ISSUE TITLE
Transaction confirmation can time out

### ISSUE THREAD

**Issue by dasein108** [urbit/bridge#501]
Bought urbit ID on opensea.io, and trying to get alive my own planet.

As I understand I should claim Master Key at bridge.urbit.org first, auth with that and only then can download necessary pem to start urbit.
So achieve that I tried to do "Transfer to Master Ticket" on the bridge, get problem on 4 step  "Transferring ID".... It's just hangs, and nothing happens.
![Screenshot 2020-07-18 at 21 34 09](https://user-images.githubusercontent.com/11820607/87856743-b892b880-c93e-11ea-9a07-aaa7e4cea993.png)
I tried 3 times, and 3 times I honestly sign transaction on MetaMask, all those tx was success but nothing more.
Some of last Tx: https://etherscan.io/tx/0xb8c55cb26b100909aa005783e446863accd67cb18c3bc0489b6f3756f70bc4ab
Where I'm wrong?

**Comment by Fang-** [comment]
How long did it hang for? Did it not proceed even after you saw the transaction go through?

This might have been a case of "transaction so slow it _looked_ like it was hanging", but you say "all those tx was success", so maybe it just didn't notice they succeeded for some reason?

If you did see the transactions you sent succeed (and these were 2-3 transactions, right?), then maybe all you still need to do is transfer it to the address listed on your master ticket, which you can do using the "transfer point/ownership" flow. Of course, that's just a workaround...

**Comment by dasein108** [comment]
maybe poor internet is guilt.

![Screenshot 2020-07-19 at 13 09 16](https://user-images.githubusercontent.com/11820607/87870146-1832a780-c9c3-11ea-9e3d-3e780a0d70c1.png)

Anyway thank you I get necessary key from address on master ticket. issue can be closed at least to me)

**Comment by Fang-** [comment]
>Timeout exceeded during the transaction confirmation process.

We'll want to handle that case better. I'll leave this open for that. Thanks!

**Comment by lukestiles** [comment]
Tracked in https://github.com/urbit/bridge/issues/556
