### ISSUE TITLE
Network Keys Not Yet Set

### ISSUE THREAD

**Issue by DeusVult8** [urbit/bridge#503]
Cannot obtain keys in Bridge. Did not breach. 
![keys](https://user-images.githubusercontent.com/36302321/87862349-0696c480-c91d-11ea-98ac-0869e10ed580.png)

**Comment by Fang-** [comment]
Updated #502 with these details, since this seems to be the same underlying issue. Closing as duplicate, thanks for filing!

**Comment by Fang-** [comment]
Actually, looking at this more closely, @DeusVult8, this is just saying that you need to set your networking keys first. There should be a "reset networking keys" button further down the page. (Did I already speak to you about this out of band? Someone else had the same problem just today. Perhaps UX/copy could be better...)
