### ISSUE TITLE
invites: we drop all invites on the floor if just one tx fails

### ISSUE THREAD

**Issue by Fang-** [urbit/bridge#509]
Copied from #506:

Consider the following, imagining that only some of the invite transactions succeeded, while some fail:

https://github.com/urbit/bridge/blob/82af1413565f05839b2551cf5451c461cce4c5e5/src/lib/useInviter.js#L186-L197

https://github.com/urbit/bridge/blob/82af1413565f05839b2551cf5451c461cce4c5e5/src/views/Invite/Email.js#L85-L91

We error out without sending emails about the invite transactions that succeeded. This is obviously Not Good (though slightly better now that the user can recover the invite codes).

I tried fixing this, but when trying to communicate intermediate and partial failure states to the user, but found myself stuck in react-final-form hell: I can only communicate successes or failures, nothing in between.

Wondering if I should just add some additional state for these situations and set those as invite logic proceeds, similar to `setStatus`... Or if there is some way to do this that's more friendly to current architecture...

**Comment by lukestiles** [comment]
@Fang- is this for stars issuing planets?

**Comment by Fang-** [comment]
Yes, but this is for the old invite flow, so it's a stale issue and can be closed (as it has eagerly been).
