### ISSUE TITLE
no eth to fund tx

### ISSUE THREAD

**Issue by h5gq3** [urbit/bridge#512]
when claiming a planet ~nolrym-fonrup I got from OS1 launch, I run into issue of no eth to pay for tx gas. the error is:

`Your ownership address 0x83E6F7A11D844E67EEecDe3E25c575Ed8431135E needs at least 0.05712 ETH and currently has 0 ETH. The transaction will automatically resume once enough ETH is available. Waiting... ▓`

I was told that the addresses are prefunded with eth so I don't need to deal with gas myself.

**Comment by liam-fitzgerald** [comment]
Is this using an invite code?

**Comment by gilletteonmeheleparim** [comment]
idk, there's four-worded code in URL after the hash sign https://bridge.urbit.org/#

**Comment by Fang-** [comment]
> I was told that the addresses are prefunded with eth

To be more precise, Bridge attempts to pay for a small handful of transactions for each ID, just enough to get you through the invite process. If someone had previously attempted to claim this same planet, but aborted or failed halfway through, then it might have already used up the "free eth" for that ID.

You can fund the transactions yourself, or ask your inviter for a new invite. This is unfortunate, but I'm not sure we can reasonably do anything about it...

**Comment by gilletteonmeheleparim** [comment]
the first time I attempted to claim this planet, it got stuck at the ethereum interaction process, didn't have any error message so I closed the window after waiting like the whole day. it probably consumed the gas then but still got stuck somewhere
