### ISSUE TITLE
Unable to access Bridge using 2/3 shard multisig

### ISSUE THREAD

**Issue by tacryt-socryp** [urbit/bridge#516]
From a user: I have the first shard and the third shard. When I try to enter bridge by putting the first shard into the first form field and the third shard into the third form field, the UI says "This field is required" on the second form field. When I try to put the third shard into the second form field instead of into the third field, it says the third field is required. This amounts to me being unable to access Bridge unless I have all three of my shards, even though I'm using 2/3 multisig. This is unacceptable. Please help!

**Comment by vvisigoth** [comment]
cc @liam-fitzgerald can take a quick look at the form validation here while @Fang- is asleep? I personally use the CLI node version of this library not infrequently and have not noted this problem.
