### ISSUE TITLE
Metamask web3 injection will disappear in Q4

### ISSUE THREAD

**Issue by Fang-** [urbit/bridge#524]
From the browser console:

> MetaMask: We will stop injecting web3 in Q4 2020.
> Please see this article for more information: https://medium.com/metamask/no-longer-injecting-web3-js-4a899ad6e59e

@liam-fitzgerald do we assume it's there, if Metamask is available, or do we always bring our own?

**Comment by liam-fitzgerald** [comment]
We always bring our own, this was changed recently.
