### ISSUE TITLE
Incorrect sigil size for stars

### ISSUE THREAD

**Issue by tylershuster** [urbit/bridge#527]
<img width="245" alt="image" src="https://user-images.githubusercontent.com/3999320/95408671-de43b400-08d4-11eb-93d5-407e61f69720.png">

**Comment by tylershuster** [comment]
Planets seem to work fine. Anyone want to send me a galaxy so I can test?

**Comment by tylershuster** [comment]
<img width="471" alt="image" src="https://user-images.githubusercontent.com/3999320/95409482-8e65ec80-08d6-11eb-8d04-37b1037c6c74.png">

**Comment by Fang-** [comment]
Closing as duplicate of #496. Thanks for filing regardless. (:
