### ISSUE TITLE
Star release page doesn't respect withdraw limit

### ISSUE THREAD

**Issue by matildepark** [urbit/bridge#540]
I even set it as high as 0.1 eth (ie. 193 gwei when ethgasstation reported 140 for ASAP) and the transaction still fails pretty quickly, "reverted by the EVM" says the JS console, though I have no idea why. 

Using a Ledger in this case, direct through Chrome. Tried hooking the Ledger through Metamask, same result.

**Comment by Fang-** [comment]
Assuming I'm looking at the right transactions/address, your withdraw limit is currently at 1, and you've already withdrawn 1 star. Is Bridge showing you information contrary to that? Guess so, it shouldn't let you send a withdraw transaction otherwise. I can look into this.

**Comment by matildepark** [comment]
<img width="339" alt="image" src="https://user-images.githubusercontent.com/20846414/103910166-833b7c00-50d2-11eb-9622-58f1af43585e.png">

<img width="497" alt="image" src="https://user-images.githubusercontent.com/20846414/103910194-89c9f380-50d2-11eb-81b0-40159d43adb8.png">

???

I'm so lost.

**Comment by Fang-** [comment]
Yeah, looks like Bridge is wrong. Guessing this was introduced in #535? Or maybe a different bug. Investigating, fix later today.

**Comment by Fang-** [comment]
Actually, to confirm: you did withdraw a star already at some point, right? But to a different address? Not sure off the top of my head how that active tab is populated, but wouldn't be surprised if it can't remember what your star were if they've been transferred someplace else.

**Comment by matildepark** [comment]
I think I did like half a year ago? Sort of figured the others would be available by now. Don't think I ever spawned it directly elsewhere. Though I kinda forget.
