### ISSUE TITLE
LinearStarRelease Contract says my withdrawLimit is 1, but Bridge says my withdrawLimit is 0 and won't let me withdraw

### ISSUE THREAD

**Issue by tacryt-socryp** [urbit/bridge#546]
High priority, as it prevents access to assets.

**Comment by philipcmonk** [comment]
I haven't seen the bridge interface for this so I'm not sure exactly what it's saying, but can you confirm that you haven't withdrawn anything yet from this address?  What the contracts call `withdrawLimit` is the *total* number that can be withdrawn (ie it doesn't depend on how many have already been withdrawn), so bridge could be subtracting `withdrawn`.

**Comment by Fang-** [comment]
Cause of this might overlap with #545, which is caused by Bridge not getting accurate responses back from the Ethereum node it's asking. Very confused by this, investigating.

**Comment by tacryt-socryp** [comment]
I believe that the LinearStarRelease contract uses `withdrawLimit` to determine the current number of available stars to withdraw: https://github.com/urbit/azimuth/blob/3a16535abb7e82842c53fe0f6e1919cd9947b4dd/contracts/LinearStarRelease.sol#L307

**Comment by tacryt-socryp** [comment]
Interesting, apparently I misunderstood how the contract works.

**Comment by Fang-** [comment]
As discussed out of band, looks like Bridge is accurate. Contract state says you've withdrawn one (1), and your current withdraw limit is one (1). Certainly hope Bridge gets this right after all the recent fixes in this area! Closing.
