### ISSUE TITLE
feature request - create a passport without an invite code

### ISSUE THREAD

**Issue by shrugs** [urbit/bridge#552]
## Problem One

Because gas prices are so high at the moment, the faucet that bridge would normally use to fund invite acceptance isn't working. This means people i send an invite to have to pay their own gas, which is annoying and also a huge drop-off in the filter (half the people i've sent a planet to haven't claimed it yet).

## Problem Two

Because the gas estimation of claiming a planet is way off (the actual transaction uses some 1/10 of the estimated gas cost (?)), anyone who needs to claim a point has to transfer way more ETH than necessary to the temp wallet, which then gets forwarded to their new passport after the transfer.

## Problem Three

There's no simple way to send that excess ETH back to another wallet, once it's owned by the management or ownership key or whatever.

## Temporary Solution

Obviously each of these problems could/should be its own issue, but there's a temporary solution that's easy enough to support. In my case, I know everyone i'm sending a planet to, and can chat with them in an existing dm or whatever, so we're able to coordinate.

One solution is to just YOLO issue a point to a person's metamask address, and then just suggest that they reticket at some point in the future. This works just fine, and lets me pay for the gas of transferring the point, which is fine.

The urbit id passport is obviously the ideal way to secure an urbit planet. I'd like to be able to tell someone "hey, create an urbit passport with this planet name", get their ownership address, and then YOLO issue the point from there. This approach lets me pay the entirety of the gas for the transfer.

## Discussion

Does a new user have to do some sort of key generation and put that on-chain? if so, i'm not sure how much this approach works, unless the new user can communicate their networking keys to me and i'm able to set those as part of the issue point transaction, though that doesn't seem like a super great UX.

**Comment by lukestiles** [comment]
This less relevant with L2.

**Comment by shrugs** [comment]
agreed!
