### ISSUE TITLE
Bridge gives no indication that transaction has timed out

### ISSUE THREAD

**Issue by ynx0** [urbit/bridge#556]
After trying to execute a transaction with really low gas, the transaction naturally timed out. 

This was indicated to me by a console message in the dev tools:
![image](https://user-images.githubusercontent.com/9275716/108829226-e8213780-7595-11eb-9c45-6ed35a5551bd.png)

However, bridge kept chugging along and did not really give any indication that anything had happened:
![image](https://user-images.githubusercontent.com/9275716/108829544-4f3eec00-7596-11eb-99b6-df1b0c0e1398.png)

There should probably be some sort of flow to get out of a transaction that timed out, or at the very least an indication of what's happened.

(Maybe even surfacing any/all errors as a popup or something so that you get bug reports faster?)

**Comment by Fang-** [comment]
Also filed in #445 and #501, so closing as duplicate. Thanks for filing regardless, it's clear this has become a real problem at this point.

**Comment by ynx0** [comment]
Whoops! Should've done some more digging before filing. Glad that it's being looked that :)
