### ISSUE TITLE
Unable to "Set Urbit networking keys"

### ISSUE THREAD

**Issue by bstro** [urbit/bridge#56]
I just installed the newest release (1.1.0) of Bridge. Upon accessing my ship for the first time, I am told that "Before you can issue child points or generate your Arvo keyfile, you need to set your Urbit networking keys." However, the link to "Set Urbit networking keys" is greyed out and unclickable. What should I do?

Thanks!

**Comment by jtobin** [comment]
When you say you've accessed your ship, have you authenticated as either its owner or its management proxy?   The action should be disabled precisely when you haven't authenticated as one of those.

Can you check that the breadcrumbs at the top of the app read something like `Bridge > Main Network > <some address>`, and that `<some address>` is the same as the one displayed under either the 'owner' or 'mgmt proxy' headers when you view your ship?

**Comment by bstro** [comment]
Interesting, `<some address>` is different than the owner proxy address. The keys to my addresses are stored on my Ledger and I'm using Bridge with that. I have access to the keys to which my ships are bound... is there something else I have to do here?

**Comment by bstro** [comment]
I've double checked the derivation path as well, it should be able to find my points and verify that I am the owner.

**Comment by jtobin** [comment]
I was just about to suggest checking your derivation path when I saw your most recent reply pop up.  

If you authenticate with MyEtherWallet/MyCrypto/etc. do you see the expected address?  MEW at least lists the HD path as `m/44'/60'/0'`, but in reality will derive addresses at `m/44'/60'/0'/0`, `m/44'/60'/0'/1`, etc.

Just on a hunch: if you authenticate to Bridge with HD path `m/44'/60'/0'/0`, do you get the expected address?

**Comment by bstro** [comment]
No points to display :(

**Comment by jtobin** [comment]
Do you get the expected address if you authenticate with MyEtherWallet/MyCrypto?

**Comment by bstro** [comment]
Yes I do, and their UI lists the HD path as `m/44'/60'/0'`

**Comment by bstro** [comment]
I FOUND it. `m/44'/60'/0'/1` :)

**Comment by bstro** [comment]
Do you happen to know if there’s any way to find the correct derivation path for a wallet without guess-and-checking it?

**Comment by jtobin** [comment]
Nope -- the most likely path is usually the "first" one in the BIP44 sense, i.e. `m/44'/60'/0'/0/0`, but some applications use other defaults (e.g. MEW/MyCrypto and `m/44'/60'/0'/0`).  But outside of using the usual default schemes as initial guesses or places to start looking, there's not much one can do.

**Comment by bstro** [comment]
Good to know, thanks for your help @jtobin !

**Comment by jtobin** [comment]
No sweat!

**Comment by Fang-** [comment]
To just chime in real quick:

> their UI lists the HD path as `m/44'/60'/0'`
> I FOUND it. `m/44'/60'/0'/1` :)

The MyCrypto UI is a bit confusing there, as it appends the zero-based index of whatever address you select in their UI to the path it displays. So, when is displays `m/44'/60'/0'` and you select the second address, that's actually the address of `m/44'/60'/0'/1`.  
(There may or may not be an off-by-one in that explanation, but you get the idea.)
