### ISSUE TITLE
Very slow to load in incognito mode

### ISSUE THREAD

**Issue by philipcmonk** [urbit/bridge#561]
`https://bridge.urbit.org/static/js/2.de79ebd6.chunk.js` is about 15MB and makes the whole thing take 15-60 seconds to load.  Not sure why the bandwidth is so low, there could be a solution there, but also 15MB seems pretty big.

**Comment by Fang-** [comment]
We're not minifying our builds right now. See also https://github.com/urbit/bridge/issues/410#issuecomment-597855487.
