### ISSUE TITLE
Download button is disabled after download

### ISSUE THREAD

**Issue by galenwp** [urbit/bridge#562]
I'm just proxying this issue, so I can't be completely certain of it. But this is understandably a bit confusing—we should let the user download the keyfile as many times as they want to on this screen (I expect).

<img width="763" alt="Screen Shot 2021-03-26 at 6 29 14 AM" src="https://user-images.githubusercontent.com/1467211/112641787-eef2d280-8dff-11eb-82f4-147734f9bc10.png">

**Comment by SudoNhim** [comment]
Browser: Google Chrome 89.0.4389.90
OS: Windows 10
Exact repro:
1) Reset the network key in bridge and wait for the keyfile download screen
2) Click to download it, choose Onedrive/Personal vault (without unlocking it first)
3) Download fails, button is now non-responsive

I was able to work around it by inspect-source on the button, but another user may be tempted to go back or refresh the page, and thus lose their keyfile.

**Comment by Fang-** [comment]
Closed via 6b72a3b. That should go into the next release, ETA early next week!
