### ISSUE TITLE
Can't click my point-name to go back to that part of bridge

### ISSUE THREAD

**Issue by rmariani** [urbit/bridge#58]
The `~lodleb-ritrul` part of this header-bar is not clickable. It looks like a hyperlink, but is not. The cursor doesn't even change into the Mickey-Mouse hand that it normally does when hovering over a clickable link. This is annoying, because I need to go back another step to `Points` whenever I want to do anything else.

https://imgur.com/a/e6XYRjR

**Comment by jtobin** [comment]
Huh, I actually can't reproduce:

![out](https://user-images.githubusercontent.com/1414434/53142549-30996980-35f9-11e9-815f-f3dea9f0156c.gif)

**Comment by Fang-** [comment]
This only affects longer names. I've seen this before. There's like an invisible sidebar covering the far right of the screen. /shrug
