### ISSUE TITLE
Ledger: doesn't work in Chrome

### ISSUE THREAD

**Issue by Fang-** [urbit/bridge#581]
On latest firmware (2.0.0). Firefox is fine, but Chrome doesn't work for some reason. Kind of the inverse of what is described [here](https://github.com/LedgerHQ/ledgerjs/blob/master/docs/migrate_webusb.md), which made me wonder if Chrome had dropped U2F support or something, but I can't find anything about that...

For readers looking for a workaround: you can use Firefox, or add your Ledger to Metamask and then login with that instead.

**Comment by eriknewton** [comment]
Just discovered that it no longer works in Safari either.

Also, while it works in Firefox, there's an additional issue using that browser: clicking on a given star in a list of stars brings up the wrong one.

**Comment by tomholford** [comment]
>which made me wonder if Chrome had dropped U2F support or something

Also having trouble finding an official source, but this appears to be the case based on these related links:

https://github.com/near/near-wallet/issues/1775
https://www.reddit.com/r/ledgerwallet/comments/nqq84s/ledger_nano_s_wont_connect_to_browser_applications/

Here's an example of supporting the new standards (HID, WebUSB) while still being able to fall back to legacy U2F for now:
https://github.com/vacuumlabs/adalite/pull/1007/files

**Comment by ngzax** [comment]
sorry to pile on, but even in FF it looks like Ledger login has issues. I tried to accept a planet in FF to my ledger wallet via the ledger login and received this error:

<img width="719" alt="Screen Shot 2021-08-17 at 8 13 58 AM" src="https://user-images.githubusercontent.com/87197/129735399-55975374-65d7-4350-8def-969b30154c27.png">

I subsequently connected to my ledger via the Metamask "bridge" method in Brave and the tx was processed fine.

**Comment by nerveharp** [comment]
Known issue, will be addressed in the next version of Bridge. Ledger themselves recommend either using Firefox or connecting your Ledger device through Metamask.
