### ISSUE TITLE
Bridge stuck on loading screen after successful login with master ticket

### ISSUE THREAD

**Issue by dietofworms** [urbit/bridge#589]
### Issue
Last night I went through the process of generating my master ticket after buying a planet. I successfully downloaded the files associated with this and had no issues until this morning when I tried logging in using bridge to get a new keyfile. I am able to successfully validate my login by entering the master ticket phrase along with my planet name however it gets stuck on this `Loading` screen. 

### What I have tried
* Tried this on both macOS using Chrome and Safari with the master ticket login;
* Tried entering the mnemonic still same problem;
* Metamask also gave the same issue after importing the seed and trying that way;
* Raspberry Pi OS using chromium still same issue;
* Entering an incorrect master ticket will correctly error as expected so I believe it's something between the validation of my identity and the loading of the bridge interface.

### Screenshots
<img width="1206" alt="Screen Shot 2021-07-01 at 2 08 52 pm" src="https://user-images.githubusercontent.com/28944297/124063385-11872e00-da76-11eb-9439-6adc49b0ed03.png">
<img width="1206" alt="Screen Shot 2021-07-01 at 2 08 59 pm" src="https://user-images.githubusercontent.com/28944297/124063387-151ab500-da76-11eb-8f81-1d37d2f224c1.png">

**Comment by dietofworms** [comment]
Additionally, I also tried on mobile with Safari - still the same issue. Almost seems like my "account" if you would even call it that is bugged somehow 😕

**Comment by dietofworms** [comment]
Javascript console outputs the following:
```
useStarReleaseStore.js
Error: Returned error: invalid opcode: opcode 0xfe not defined
    at Object.ErrorResponse (errors.js:28)
    at index.js:303
    at XMLHttpRequest.i.onreadystatechange (index.js:98)
(anonymous) @ useStarReleaseStore.js:53
c @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
l @ asyncToGenerator.js:29
Promise.then (async)
r @ asyncToGenerator.js:13
o @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ Points.js:203
Rl @ react-dom.production.min.js:262
t.unstable_runWithPriority @ scheduler.production.min.js:18
zi @ react-dom.production.min.js:122
Pl @ react-dom.production.min.js:261
(anonymous) @ react-dom.production.min.js:261
N @ scheduler.production.min.js:16
_.port1.onmessage @ scheduler.production.min.js:12
```

**Comment by Fang-** [comment]
Thank you for the detailed report! I'll look into this today.

> `useStarReleaseStore.js`

We need to take it out back and... give it a good talking to.

**Comment by dietofworms** [comment]
@Fang- just tried again and I'm getting this error now:
[bridge.urbit.org-1625132664470.log](https://github.com/urbit/bridge/files/6747177/bridge.urbit.org-1625132664470.log)

Note: I tried with and without Metamask and still same issue.

**Comment by Fang-** [comment]
It's expected to still see that error in the browser console. Does it also still keep you stuck on the "loading.." screen? Could you share which Ethereum address you're logging in with?

**Comment by dietofworms** [comment]
>Does it also still keep you stuck on the "loading.." screen? 

Yes same as before unfortunately.

>Could you share which Ethereum address you're logging in with?

0x91c9796CCD8103a0EdE36F5f16fD02088ECE2B18

**Comment by Fang-** [comment]
Thanks, I can reproduce this now. Investigating...

**Comment by Fang-** [comment]
Alright @dietofworms, v2.9.2 is live now, and should contain both fixes for this issue. I think (and hope!) this is the last of it, but let me know if you have any further trouble.

**Comment by dietofworms** [comment]
@Fang- looks like that has fixed it. I am able to log in successfully with my master key. Thank you for your quick response on this one.
