### ISSUE TITLE
Dropdown item spacing is off

### ISSUE THREAD

**Issue by Fang-** [urbit/bridge#6]
<img width="266" alt="image" src="https://user-images.githubusercontent.com/3829764/51222200-90616e00-18f1-11e9-911d-0a34e241c368.png">

**Comment by gavinpatkinson** [comment]
Firefox?

**Comment by Fang-** [comment]
Yes. (^:

**Comment by alexmatz** [comment]
bundled with other UI issues and assigned to @c-johnson
