### ISSUE TITLE
Can't accept transfer proxy because transaction won't ever send despite gas price being double the recommended value

### ISSUE THREAD

**Issue by tacryt-socryp** [urbit/bridge#624]
The transaction won't even get submitted into the mempool to show up as pending.

Is Bridge's ETH node working right now? @jalehman @Fang- @philipcmonk

**Comment by tacryt-socryp** [comment]
It worked on the 5th time, but the other 4 times didn't ever get submitted to the mempool. Really weird shenanigans, and it took 45 minutes of trying.

**Comment by Fang-** [comment]
As mentioned out of band, Bridge depends on Infura, which should generally be quite reliable.

There may or may not be some cases where transactions with exceptionally low fees struggle to propagate through the network, not show up in explorers etc. Was this the case? Were you getting any messages at all or just a static tx sending progress bar?

**Comment by tacryt-socryp** [comment]
Static tx pending in the status bar. Fees were set at 180 gwei gas rate while the "high gas fee / fast transaction" recommended was 130.
