### ISSUE TITLE
Duplicate points when same address used for different proxies

### ISSUE THREAD

**Issue by yosoyubik** [urbit/bridge#634]
If you log in with a private key, when an address is attached to multiple proxies (e.g. is both an owner proxy and a management proxy), it will show duplicate ships in the Points view:

<img width="496" alt="Screen Shot 2021-09-24 at 9 41 23 AM" src="https://user-images.githubusercontent.com/1033194/134637335-f2abed72-a1d9-4555-a4ff-3faa63ba33a5.png">

For context, this is the ownership map:

<img width="744" alt="Screen Shot 2021-09-24 at 9 42 31 AM" src="https://user-images.githubusercontent.com/1033194/134637407-38e97748-9cfa-4681-9aee-0e46355a825a.png">

**Comment by Fang-** [comment]
Might be a duplicate of #526. (This case specifically, duplicate of the most recent comment there.)

**Comment by yosoyubik** [comment]
Yes, that's right, closing in favor of that one
