### ISSUE TITLE
Minor UI issues around network seed entry

### ISSUE THREAD

**Issue by jtobin** [urbit/bridge#65]
There seems to be a UI bug in the validation for the network seed input, such that a green box will appear around the network seed even if it is in fact invalid.

Additionally: the network seed input should probably accept both `0x`-prefixed and unprefixed hex strings.

**Comment by divraj** [comment]
bug still exists when asked to enter network seed for public key generation , I entered an alphanumeric key based on the instructions.

**Comment by Fang-** [comment]
A fix for network seed entry in general is in the pipeline: #85. No more futzing around with manual entry once that gets merged!

**Comment by alexmatz** [comment]
@Fang- can I close this now that #85 has been merged?

**Comment by Fang-** [comment]
You're right, this can be closed!
