### ISSUE TITLE
The action next to Set Network Keys in the ID section should simply say "Set"

### ISSUE THREAD

**Issue by jalehman** [urbit/bridge#669]

**Comment by nerveharp** [comment]
1. The Network Keys function now lives in the "OS" section. Not sure if this was decided and resolved out of band.
2. The Network Keys function itself now either has the actions "Initialize," or "Reset" and "View."

Unkeyed point:
![image](https://user-images.githubusercontent.com/748181/144635955-8feef944-2b80-473a-b268-6fad6dd27796.png)

When network keys have been set:
![image](https://user-images.githubusercontent.com/748181/144635842-bb2f55d7-d07e-46d2-aaf1-eb81df478d3d.png)

@jyng Can you confirm this matches your intent?
