### ISSUE TITLE
Update planet code wallet generation logic

### ISSUE THREAD

**Issue by jalehman** [urbit/bridge#674]
Generating wallets is slow, and if we have to generate each one upon visiting the UI it locks everything up. There isn't really a way around this technically, so we'll design around it.

Instead of displaying the generated wallet as the invite code, display the @p of the planet. Pressing the "Copy" button should result in the wallet being generated, at which point a single loading indicator can replace the copy button to indicate the work being done.

If a CSV is downloaded, it will take a long time, at which point a modal should show up that indicates that the CSV is being prepared. Copy should indicate that this operation will take some time and to please be patient. The option to cancel the operation should be provided.

**Comment by willbach** [comment]
Proposed change after some discussion with @jyng : 
<img width="473" alt="Screen Shot 2021-10-30 at 3 04 48 PM" src="https://user-images.githubusercontent.com/7759384/139555550-8581155f-e808-4530-a480-263a596f39fb.png">
