### ISSUE TITLE
Error prevents accessing ID or OS screens on newly spawned stars under ~zod

### ISSUE THREAD

**Issue by jalehman** [urbit/bridge#676]
Probably has something to do with setting networking keys. To reproduce:

1. Log in as ~zod/~zod
2. Spawn a new star
3. Log out
4. Log in as ~zod/~zod again
5. Click the newly spawned star point
6. Error

After some amount of time, the error goes away. Isn't that great?

<img width="1112" alt="Screen Shot 2021-10-29 at 10 55 40 AM" src="https://user-images.githubusercontent.com/550978/139480946-dd2c28aa-d4c0-478b-b0c0-c7fc10919e7e.png">

**Comment by willbach** [comment]
Can't reproduce
