### ISSUE TITLE
Fix URL link for Invite Codes

### ISSUE THREAD

**Issue by jyng** [urbit/bridge#682]

**Comment by jyng** [comment]
![image](https://user-images.githubusercontent.com/9557907/139491903-ac2669a5-69c3-46a3-addd-6a2a0a350b2b.png)

**Comment by nerveharp** [comment]
![image](https://user-images.githubusercontent.com/748181/144632042-075008b3-b29f-4316-a5c5-82e0de1eb8b5.png)

I have a feeling this pertained to the font-family (Inter, rather than Source Code Pro) and everything else seems to be fine, so closing.
