### ISSUE TITLE
All @p should use monospace

### ISSUE THREAD

**Issue by jyng** [urbit/bridge#683]

**Comment by jyng** [comment]
![image](https://user-images.githubusercontent.com/9557907/139493604-791013c1-bb83-4750-a6ba-987897c2ac5a.png)

**Comment by nerveharp** [comment]
Haven't seen a single ~patp not in monospace.

**Comment by nerveharp** [comment]
Reopening; found one more:
![image](https://user-images.githubusercontent.com/748181/144649831-c84f70f7-80fe-4a71-a795-acfc84b38576.png)

**Comment by nerveharp** [comment]
Confirmed.

![image](https://user-images.githubusercontent.com/748181/144875227-517702a4-fdd7-4180-bab7-3b8273918f1a.png)

**Comment by jyng** [comment]
Ships in family view aren't monospaced
![image](https://user-images.githubusercontent.com/9557907/145084643-8e748058-345a-4124-96c3-75a8854b2669.png)

**Comment by jyng** [comment]
Found another one inside Migrate
![image](https://user-images.githubusercontent.com/9557907/145085557-3a3d8ca4-3b6d-49a1-b993-73dd8d62ee7f.png)
