### ISSUE TITLE
Transfer L2 points shows up as an L1 acceptance

### ISSUE THREAD

**Issue by yosoyubik** [urbit/bridge#686]
Transferring a L2 star (by setting the transfer-proxy to the address of the new owner) shows up as an L1 transfer acceptance

**Comment by yosoyubik** [comment]
Screenshots:

<img width="489" alt="Screen Shot 2021-10-31 at 3 53 13 PM" src="https://user-images.githubusercontent.com/1033194/139589357-b7c32ddd-4ada-4a30-b162-08562b9eae7e.png">
<img width="729" alt="Screen Shot 2021-10-31 at 3 53 06 PM" src="https://user-images.githubusercontent.com/1033194/139589359-fc4ccbbe-48d6-45bc-b90d-f1f97c073c42.png">

**Comment by willbach** [comment]
Is the receiving star on L2 or L1?

**Comment by yosoyubik** [comment]
On L2 (`~norsyr`). I'm transferring it to `0xf480...`—you can see the transfer-proxy address—and that's done with a L2 tx, but when I log in using `0xf480...` ~norsyr is shown as on L1, and the acceptance tx is an L1 tx.
