### ISSUE TITLE
Activation flow should use 14px as the base font

### ISSUE THREAD

**Issue by tomholford** [urbit/bridge#692]

**Comment by nerveharp** [comment]
![image](https://user-images.githubusercontent.com/748181/144634291-aaeaaa4d-8f62-46b6-8235-8c7822476e32.png)

@jyng confirming that this is what you desire:
1. Title is set in 16px bold
2. Step description is set in 14px regular
3. Alerts are set 16px regular
4. This single "Copy" button is set in 18px regular

**Comment by tomholford** [comment]
addressed in #698
