### ISSUE TITLE
App container width changes when "Master Ticket"/"Recovery Phrase" option is selected

### ISSUE THREAD

**Issue by urcades** [urbit/bridge#695]
Check out the video below:

https://user-images.githubusercontent.com/1195363/139772141-fd7d82f7-1da1-4abb-9cf1-80d5268ea7fc.mov

Note the edges of the primary container expand outward slightly when I click either "master ticket" or "recovery phrase" options.

**Comment by jyng** [comment]
This seems to be the case for other login options as well
