### ISSUE TITLE
Going back is odd/unintuitive

### ISSUE THREAD

**Issue by rcrdlbl** [urbit/bridge#7]
Copying this directly from the twitter thread I started –

it feels kinda awkward that the back button/back gesture in the browser takes you away from bridge – I think this stems from the fact that bridge's UI takes up the entire page and therefore sends the message that each view is in fact a separate browser page

The only way to go back (during setup at least) is to click on the path at the top which isn’t totally unintuitive; but it isn’t the first thing most people would try — the thing they try leads to them leaving bridge then returning all the way back to the start screen

The most obvious way would be a back button next to the continue button imo – much easier to notice

**Comment by galenwp** [comment]
Did we close because it's fixed, or being fixed elsewhere? I agree that this is confusing / annoying.

**Comment by rmariani** [comment]
This is maybe the biggest problem with bridge IMO

**Comment by urbitalex** [comment]
This is being worked on right now. Closed it to avoid any duplication of work.
