### ISSUE TITLE
ID and OS buttons unclickable for L1 assets

### ISSUE THREAD

**Issue by Fang-** [urbit/bridge#702]
1) Log in as ~zod on ropsten L2 bridge,
2) Select ~zod.
3) Try to click "ID" or "OS", nothing. Doesn't trigger errors in the browser console either. Clicking "Galaxy ops" works fine. Observe similar behavior for its other stars.
4) Switch to ~nilzod, observe the buttons navigate correctly.

May or may not be related to #676?

**Comment by willbach** [comment]
Can't reproduce at https://bridge-dev.urbit.org/

**Comment by Fang-** [comment]
Turns out this is a problem with Metamask having the wrong network selected. As per #510, we should just inform the user of mismatches like these.

Still very strange behavior though.
