### ISSUE TITLE
Spawning page inaccessible for L1 assets

### ISSUE THREAD

**Issue by Fang-** [urbit/bridge#703]
For L2 stars, I can "star ops" -> "spawn planets" just fine. This is not the case for L1 stars or galaxies. Additionally, for galaxies, the senate page is greyed out as well, I cannot click it to navigate.

<img width="578" alt="image" src="https://user-images.githubusercontent.com/3829764/140173926-febc947b-36c0-4c4a-a6ea-a784cb8794fe.png">

**Comment by willbach** [comment]
This may be related to #702 , the general issue being that the interface doesn't consider L1 points eligible to spawn or otherwise interact

**Comment by willbach** [comment]
I can't reproduce this at https://bridge-dev.urbit.org/
