### ISSUE TITLE
L2 roller timer may display a negative number

### ISSUE THREAD

**Issue by Fang-** [urbit/bridge#704]
I wasn't in time for the screenshot, but briefly after the roller time came around, the remaining time displayed was negative. That is, it had a leading `-`.

Should probably replace the time with "rolling..." or w/e when it's near zero or negative seconds remaining.

(Additionally the txs are still sitting in queue and roller state of these isn't being communicated clearly, but I'm not sure what expected behavior there is rn and it's out of scope for this issue anyway.)

**Comment by willbach** [comment]
There should only ever be a second or so of lag, so I'll just default the timer to 0

**Comment by lukestiles** [comment]
Closing as this appears to be fixed by the PR.
