### ISSUE TITLE
WalletConnect design should be improved

### ISSUE THREAD

**Issue by jyng** [urbit/bridge#708]
Current Flow:
`WalletConnect` > "Scan QR Code" > (third-party wallet connection) > `Authenticate` > (thirdparty wallet sign) > `Authenticate` / `Disconnect`

**Comment by jyng** [comment]
### While the user is connecting via WalletConnect — after the QR Code disappears

![WalletConnect - Loading](https://user-images.githubusercontent.com/9557907/141129851-1aba02a6-a005-4225-962a-048eaf777e55.jpg)


### Once it's done loading OR they've logged in before with a third-party wallet (Metamask or WalletConnect). 

Clicking `X` would disconnect the wallet (thus allowing them to connect to a different wallet of their choosing). Clicking `>` would proceed them into the wallet.

Note: The WalletConnect logo should be replaced with the respective logo of their wallet (i.e. Rainbow, Argent, Trust, etc)

![WalletConnect - Logged In](https://user-images.githubusercontent.com/9557907/141129289-b2da9204-f724-4fb8-979c-1435dd0bc01f.jpg)
)


### If the user reaches an error connecting to a third-party wallet
![WalletConnect - Error](https://user-images.githubusercontent.com/9557907/141129488-b6409850-e945-4613-8930-7d45bcf521be.jpg)

**Comment by nerveharp** [comment]
This has been reviewed and is complete.
