### ISSUE TITLE
A recent spawned point doesn't show up on the dropdown

### ISSUE THREAD

**Issue by yosoyubik** [urbit/bridge#717]
**Describe the bug**

You have to log out to select the point, but it still doesn't show up (it did show up after some point)

<img width="1073" alt="Screen Shot 2021-11-04 at 5 24 26 PM" src="https://user-images.githubusercontent.com/1033194/140383119-649346b0-8831-4c35-abd2-efc774b2784c.png">

Clicking on both ID and OS was unresponsive.

**To Reproduce**
1. Spawn a star
2. Click on dropdown

**Expected behavior**
It should show the newly spawned star

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14.6
 - Browser: Brave
 
**Login method (please complete the following information):**
- Maste Ticket

**Comment by drbeefsupreme** [comment]
I found a workaround by clearing cookies and force refreshing, using the Edge browser.
