### ISSUE TITLE
no option to set galaxy spawn proxy to L2

### ISSUE THREAD

**Issue by drbeefsupreme** [urbit/bridge#719]
**Describe the bug**
By #707, Bridge crashes when you click to Migrate to L2 for a galaxy. However you can still reach the Migrate to L2 interface by having a star at the same address and click Migrate to L2 there, and then select the galaxy from the dropdown menu. For the star, it gives the option of setting spawn proxy to L2 or migrating to L2, but for the galaxy it displays neither. Galaxies should be able to set their spawn proxy to L2.
 
**To Reproduce**
1. Login to a wallet with both a galaxy and a star.
2. With the star selected from the dropdown box, click Migrate to L2.
3. From the Migrate UI, click the dropdown box and set it to a galaxy.

**Expected behavior**
Galaxies should have the option to set spawn proxy to L2.

**Screenshots**
https://i.imgur.com/7Mb2k4z.png

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge

**Login method (please complete the following information):**
Master Ticket

**Additional context**
Almost all stars are already spawned and in lock-up contracts, so this is probably pretty low priority.

**Comment by drbeefsupreme** [comment]
So it is possible to set the spawn proxy to L2 manually, by following the set spawn proxy flow and inputting `0x1111...`. However, this seems to break the ability to spawn stars, with a `Invalid JSON response`:

https://i.imgur.com/0OPH6hw.png-

Clicking on Reset Transaction just hangs on this screen, and you cannot click on Generate and Sign Transaction

https://i.imgur.com/baCGTfG.png

**Comment by willbach** [comment]
Updated:
<img width="543" alt="Screen Shot 2021-12-07 at 11 42 53 AM" src="https://user-images.githubusercontent.com/7759384/145070365-6e612c4c-50ec-4a1e-a141-98caf0138dc0.png">
