### ISSUE TITLE
Cannot set spawn proxy to custom value anywhere

### ISSUE THREAD

**Issue by Fang-** [urbit/bridge#720]
I am logged in as a star. Supposedly the option to set the spawn proxy should be visible under the ID section, but its' not there:

<img width="508" alt="image" src="https://user-images.githubusercontent.com/3829764/140383644-7d456c96-50d5-4daf-9b02-8becbd7ac91c.png">

This is the case both with and without networking keys set.

**Comment by drbeefsupreme** [comment]
I'll note that Set Spawn Proxy does appear for galaxies, so this seems to be specific to stars.

**Comment by drbeefsupreme** [comment]
I was able to get Set Spawn Proxy to appear for a star by first using Migrate to L2 to set the spawn proxy to L2. Then Spawn Proxy Address appeared under ID, and I was then able to set the spawn proxy to another address (which shouldn't be possible, but is a separate issue I will file).

**Comment by drbeefsupreme** [comment]
I was able to set the spawn proxy after setting networking keys as well, without migrating to L2.

**Comment by lukestiles** [comment]
Closing per @drbeefsupreme reproduction comments.
