### ISSUE TITLE
Unable to set Transfer Proxy for an L2 point

### ISSUE THREAD

**Issue by tomholford** [urbit/bridge#724]
Steps to reproduce
1. Spawn an L1 star
2. Migrate to L2
3. Under ID > Ownership, click Transfer, and attempt to change the proxy

**Comment by yosoyubik** [comment]
I'm unable to reproduce this. I've tried with two stars and they both get accepted:

<img width="1128" alt="Screen Shot 2021-11-05 at 2 30 37 PM" src="https://user-images.githubusercontent.com/1033194/140521700-590a7188-daba-4568-8cca-c9c7cdf6b539.png">

<img width="492" alt="Screen Shot 2021-11-05 at 2 55 36 PM" src="https://user-images.githubusercontent.com/1033194/140521730-09176354-84af-43c3-a879-54cdaf62a7ce.png">

**Comment by yosoyubik** [comment]
After doing some incantations, I was able to reproduce a _similar_ issue that was causing Bridge to receive a wrong predicted L2 nonce.

I have a fix for it here: https://github.com/urbit/urbit/commit/e54805893f0f48d8fc62642f4311fe6efc534913

**Comment by nerveharp** [comment]
I was able to change the transfer proxy for a L2 star, albeit with keys set:

![image](https://user-images.githubusercontent.com/748181/144650164-0b0236af-770c-4a35-9864-a2635e472914.png)
