### ISSUE TITLE
After migrating a star, it still shows as on L1

### ISSUE THREAD

**Issue by yosoyubik** [urbit/bridge#728]
**Describe the bug**
Once the migration flow of a star is done and you go back to the home page, the dropdown still shows the star as on L1

**To Reproduce**
1. Migrate a star
2. Go to Home view
3. Click on Dropdown

**Expected behavior**
It should say ~norrys L2

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14.6
 - Browser: Brave
 
**Login method (please complete the following information):**
- Maste Ticket
- 
<img width="594" alt="Screen Shot 2021-11-04 at 5 52 26 PM" src="https://user-images.githubusercontent.com/1033194/140385712-c1e04438-b1bb-4d70-bfd7-531c15e3622a.png">

**Comment by drbeefsupreme** [comment]
I had the same issue, but it looks like it eventually shifted to say L2.
