### ISSUE TITLE
using existing planet, Bridge "generate keyfiles" does not prefill network seed if logged in with master BIP39

### ISSUE THREAD

**Issue by BernardoDeLaPlaz** [urbit/bridge#73]
Does work if logged in with Management proxy BIP39, though.

**Comment by Fang-** [comment]
>master BIP39

Does it work if you log in with the master *ticket*? ie the thing that looks like a long ship name.

**Comment by BernardoDeLaPlaz** [comment]
<checks>

yes, it does work

**Comment by Fang-** [comment]
Ah, that's it then. You were logging in with the BIP39 *ownership seed*, which is derived from the master ticket, but which isn't in the same derivation branch as the networking seed. Thus, it wasn't able to derive that and pre-fill it for you.

Putting ownership seed alongside the master ticket might've been confusing...

**Comment by vvisigoth** [comment]
@rmariani @urbitalex can we make sure that this is more clearly documented in bridge or in docs?

**Comment by rmariani** [comment]
Yeah, I will indicate what the implications of choosing master ticket vs BIP 39 are
