### ISSUE TITLE
Cannot do specific spawns on L2

### ISSUE THREAD

**Issue by Fang-** [urbit/bridge#731]
I am logged, through Metamask, as a star's owner. I have set its spawn proxy to be on L2. 

I have two ways to spawn planets:
- As planet codes, which gives me a random planet + master ticket
- As L1 spawns, which let me choose a planet and target address

Being able to do the latter is a bit confusing, I thought I designated spawns to happen on L2 for this star.  
Worse: I cannot spawn specific planets to specific addresses on L2. This functionality exists on L2 in the same way it does on L1, so Bridge should probably expose it.

**Comment by lukestiles** [comment]
@Fang- is this still an issue after PR #795 ?
