### ISSUE TITLE
can transfer galaxy to L2

### ISSUE THREAD

**Issue by drbeefsupreme** [urbit/bridge#732]
**Describe the bug**
Trying to migrate a galaxy to L2 via the method in #707 doesn't work. But following the method in #719, you can reach this screen and despite there not being any radio buttons, you can click on "Transfer point to Layer 2" and the transaction will go through, and the galaxy will now be on L2.

**To Reproduce**
Follow the steps in #719 and click Transfer point to Layer 2.

**Expected behavior**
There shouldn't be any way to transfer a galaxy to L2, besides transferring the point and inputting the L2 deposit address manually.

**Screenshots**
https://i.imgur.com/7Mb2k4z.png
https://i.imgur.com/J57ZtEl.png

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 

**Login method (please complete the following information):**
Master ticket

**Additional context**
This is a footgun that someone could lose their galaxy with, so I think release ought to be blocked on this.

**Comment by drbeefsupreme** [comment]
Also, attempting any further transactions using the galaxy at this point fails (as it ought to):

https://i.imgur.com/MIbAPd4.png

**Comment by jalehman** [comment]
Mainnet will prevent this from happening, but the design should reflect that you can't move a galaxy to L2.
