### ISSUE TITLE
can perform a L1 set spawn proxy action after setting spawn proxy to L2 with a star

### ISSUE THREAD

**Issue by drbeefsupreme** [urbit/bridge#733]
**Describe the bug**
By #720 by default there is no way for a L1 star to manually set their spawn proxy. But if you migrate the star's spawn proxy to L2, the interface to set the spawn proxy appears. At this point, you should be able to set the spawn proxy as a L2 transaction. However, using this interface, it looks like it sends another L1 change spawn proxy action. I'm pretty sure Azimuth should reject  since the spawn proxy was already on L2? But it seems to go through, and it returns the star to the state where Set Spawn Proxy no longer appears as an option, but also the Migrate to L2 option is now gone as well.

EDIT: The Azimuth behavior is expected since Ropsten doesn't have the contract upgrades. But this is still a Bridge issue.

Here are the Ropsten transactions displaying this behavior:
Setting spawn proxy to L2: https://ropsten.etherscan.io/tx/0x23ab24f3c66cd19fcbdb0a35e36614e4218f5924e3aa3bc2e4beea5cc8c45250
Setting spawn proxy to another address as a L1 transaction:
https://ropsten.etherscan.io/tx/0x81560c4224dd70c1b022a1f9007401ebc42acbfbab719cf7b095383e82b46347

**To Reproduce**
1. Spawn a star
2. Set networking keys
3. Click Migrate to L2 from the dropdown menu
4. Set the spawn proxy to L2
5. Return to home screen
6. Click on ID
7. Use Set Spawn Proxy to set it to a new address.

**Expected behavior**
Once you migrate to L2, setting the spawn proxy ought to be done with a L2 transaction. Furthermore, the ability to set the spawn proxy shouldn't vanish once you do this.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge

**Login method (please complete the following information):**
Master ticket

**Additional context**

**Comment by drbeefsupreme** [comment]
Tried spawning a planet, and Bridge did a L1 transaction for it and it succeeded. https://ropsten.etherscan.io/tx/0xa92b54242077c8d38c09ef8c714cbe9926c7fdb77e534e0edfcaaacb34004cf5

**Comment by drbeefsupreme** [comment]
According to @philipcmonk Ropsten doesn't have the latest Azimuth contract upgrades, so there isn't actually an issue with Azimuth here (phew!). It is still a Bridge issue though.

**Comment by nerveharp** [comment]
@drbeefsupreme can you confirm this is still at large, or fixed?
