### ISSUE TITLE
logging in as a proxy is not revealed anywhere on the UI

### ISSUE THREAD

**Issue by drbeefsupreme** [urbit/bridge#734]
**Describe the bug**
If you set the spawn/management proxy of a star to another address and then log in at that address, nothing on the page appears to show you that you're looking at a proxy.

**To Reproduce**
1. Set spawn proxy of a star
2. Login as spawn proxy

**Expected behavior**
It ought to be surfaced somewhere in the UI that you're logged in as a proxy.

**Screenshots**
Logged in as a star's spawn proxy:
https://i.imgur.com/MYOvywy.png

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge

**Login method (please complete the following information):**
Master ticket (I set the spawn proxy to the address of a master ticket for another point, to avoid the issue of seeing multiple identical points on the login screen from #526 and so not being able to tell which was the proxy)

**Additional context**
Clicking on ID and OS doesn't do anything. You should be able to set your spawn proxy from your spawn proxy, so you ought to be able to access ID. This is a separate issue though I will file.

**Comment by Fang-** [comment]
Ah, this explain the feeling I got that something was missing from the point overview page! Current Bridge separates the assets out by the level of control you have over them. No shortage of ways to communicate that, but we should pick/keep at least one.

**Comment by drbeefsupreme** [comment]
I should mention that this may also be the case for management proxy, just haven't gotten around to testing it yet.

**Comment by drbeefsupreme** [comment]
Confirmed today that this also applies to management proxies.

**Comment by willbach** [comment]
I'm going to close in favor of #804 , since that will entail some design work and also encompasses ownership
