### ISSUE TITLE
Cannot access ID and OS pages as a spawn proxy

### ISSUE THREAD

**Issue by drbeefsupreme** [urbit/bridge#736]
**Describe the bug**
The first Azimuth update this year introduced the ability for proxies to set themselves to a new address. Currently this is not possible (at least with spawn proxies, haven't gotten to testing management proxies yet), since you cannot access the ID page when logged in as a spawn proxy. You also can't access the OS page, but that ought to be the case (though probably it shouldn't display it at all).

**To Reproduce**
1. Spawn a star
2. Set their spawn proxy
3. Login as spawn proxy
4. Clicking on ID doesn't do anything, so you cannot access the page to set the spawn proxy.

**Expected behavior**
When logged in as a spawn proxy you should be able to set your spawn proxy from the ID page.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 
**Login method (please complete the following information):**
Master ticket (via same method as #734)

**Comment by jyng** [comment]
Was this star on L1? Cause I had the same error with a L1 star but not a L2 star

**Comment by lukestiles** [comment]
Closing per https://github.com/urbit/bridge/issues/746#issuecomment-968295444. Will reopen if there are more reports.
