### ISSUE TITLE
Endpoint as ws:// considered insecure when serving on https://

### ISSUE THREAD

**Issue by Fang-** [urbit/bridge#74]
Can only reproduce when running with `npm run pilot`, not when serving the `build/` after doing `npm run build`, for some reason.

It points [here](https://github.com/urbit/bridge/blob/master/src/views/Network.js#L48-L49). Looking up the error points you to results like [this](https://stackoverflow.com/questions/13348766/securityerror-the-operation-is-insecure-window-history-pushstate#13348807), which suggest it's against security guidelines to make any requests to different domains/over different protocols when serving over https. So, the `ws://` endpoint is considered insecure here.

Why are we connecting over websockets anyway? cc @jtobin

**Comment by philipcmonk** [comment]
Worth noting that `ws://` *is* insecure; `wss://` is the secure version.  In this case, it looks like we're going to localhost, though.

**Comment by Fang-** [comment]
Hah, good call @philipcmonk, using `wss://` actually fixes it. PR incoming!
