### ISSUE TITLE
Download Passport interaction should stay on the page, but doesn't seem to be working either

### ISSUE THREAD

**Issue by jyng** [urbit/bridge#742]
When pressing `Download Passport`, it shouldn't redirect to this page, it should just download.

However, it doesn't seem to be working here either.
![image](https://user-images.githubusercontent.com/9557907/140787894-2cb43d80-3198-4f44-bbfb-8766eac298c0.png)

**Comment by willbach** [comment]
currently blocked on this PR: https://github.com/urbit/PaperRenderer/pull/157
