### ISSUE TITLE
Clicking `Migrate` should not open a popup

### ISSUE THREAD

**Issue by jyng** [urbit/bridge#743]
This interaction behavior is incorrect. The popup should only show to New Users, with a checkbox `Do Not Show Again`
![image](https://user-images.githubusercontent.com/9557907/140788634-8add2eac-e47c-4a8e-883a-435daf7d1931.png)

**Comment by willbach** [comment]
@jyng should the Migrate button be in the dropdown or on the star page itself? It seems more intuitive to put it on the star page and on the home page.

**Comment by jyng** [comment]
The Migrate action should be in the dropdown. What I'm seeing that's incorrect is that the migration action isn't consistent across ships views. It should only unavailable if there they are no more L1 ships.

 An additional logic here would be that if the ship (~fallyn-balfus) they are clicking from is on L1, we would preselect that ship (~fallyn-balfus) in the transaction screen.

![Dropdown Open](https://user-images.githubusercontent.com/9557907/141364025-b86fc4ff-90b6-4447-94de-1b84898eedad.jpg)

![Migration Transaction - Prefilled](https://user-images.githubusercontent.com/9557907/141362285-1c87b1bc-dc76-46d6-a7ba-f7b885e65eca.jpg)

If the ship is on L2 or if they clicked `Migrate L1->L2` from Family View, the ship selection would be empty.

![Dropdown - Family](https://user-images.githubusercontent.com/9557907/141364430-28c95f34-58ec-4dcc-a505-f278bcde4bf4.jpg)

![Migration Transaction - Empty](https://user-images.githubusercontent.com/9557907/141362553-008cf283-3225-42cf-895b-6c1d919321be.jpg)


There's also additional migration behavior that's not happening.
In the designs, I have it where if you go to an L1 ship (star and planet), a Migration popup should come up. This should also tell them where to access the migration should they chose to close the popup.

![Migration Popup](https://user-images.githubusercontent.com/9557907/141360013-f3304e33-24d4-41a6-9cd2-1ddd41bfee7a.jpg)

**Comment by willbach** [comment]
Ok. There's a lot of missing state necessary to support this. I'm working on making it more cohesive. I think the popup is already there, but there are some issues with the popup on these screens
