### ISSUE TITLE
Cannot access ID and OS pages from L1...sometimes

### ISSUE THREAD

**Issue by jalehman** [urbit/bridge#746]
This is possibly related to #736

ID and OS pages are sometimes inaccessible. This is, sadly, a heisenbug.

I'm getting these console errors at a time when I'm running into this:
<img width="484" alt="Screen Shot 2021-11-08 at 5 14 30 PM" src="https://user-images.githubusercontent.com/550978/140843664-9e2d043e-cf57-4c6a-ac4c-58ed16b4a3db.png">

**Comment by willbach** [comment]
@jalehman I was able to reproduce when trying to use a version of bridge that was pointed at Ropsten while Metamask was pointed at mainnet. Pointing Metamask at Ropsten fixed the issue
