### ISSUE TITLE
`Returned error: invalid sender` has returned

### ISSUE THREAD

**Issue by jalehman** [urbit/bridge#749]
_Update: this issue occurs whenever Metamask is pointing to a network other than the one that Bridge is._

<img width="1162" alt="Screen Shot 2021-11-08 at 4 43 36 PM" src="https://user-images.githubusercontent.com/550978/140840941-df715f72-bd08-4dce-8246-ffebd5722fe8.png">

**Comment by willbach** [comment]
Going to close this since it has not occurred since the solution (set Metamask network) has been implemented.
