### ISSUE TITLE
Chain ID selection during transaction signing in offline mode is ugly

### ISSUE THREAD

**Issue by Fang-** [urbit/bridge#75]
It currently allows you to input any arbitrary number. We should have a dropdown there for [valid values](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md), or at least the popular/commonly used ones, and perhaps a "custom..." option to cover edge cases.

**Comment by c-johnson** [comment]
Fixed by https://github.com/urbit/bridge/pull/100
