### ISSUE TITLE
Sometimes I can't spawn planets on L1

### ISSUE THREAD

**Issue by jalehman** [urbit/bridge#751]
I'm not sure why this happens, but at times I don't have the ability to spawn planets from L1:
<img width="633" alt="Screen Shot 2021-11-08 at 4 58 59 PM" src="https://user-images.githubusercontent.com/550978/140842373-8cb18892-6942-42f4-9439-918ac15e8c72.png">

I can't spawn L1 stars from `~zod` either:
<img width="662" alt="Screen Shot 2021-11-08 at 5 01 00 PM" src="https://user-images.githubusercontent.com/550978/140842443-557a90b8-3ce2-4516-8811-8fadf81c26de.png">

But for some reason, I *can* spawn planets on L2 from the L1 planet spawning menu:
<img width="630" alt="Screen Shot 2021-11-08 at 5 01 16 PM" src="https://user-images.githubusercontent.com/550978/140842473-9800ad01-a7a1-4a4c-9144-ebede5d0ae36.png">

Perhaps the wrong bit has been flipped?

**Comment by willbach** [comment]
This was either a network mismatch issue or network keys were not set for the star (I just encountered and fixed that)
