### ISSUE TITLE
Invite-related L2 transactions sent out of order

### ISSUE THREAD

**Issue by yosoyubik** [urbit/bridge#761]
Sometimes the order in which invite transactions are sent is not preserved.

The order in which they should be sent is:
1. spawn                 (ownership nonce)
2. configureKeys   (nonce = 0)
3. setMgmtProxy.  (nonce = 1)
4. Transfer             (nonce = 2)

but in some cases setMgmtProxy is sent before configureKeys, causing 2. and 3. to fail, since they are applied in order in the roller

Order in the code:

<img width="502" alt="Screen Shot 2021-11-10 at 12 15 42 PM" src="https://user-images.githubusercontent.com/1033194/141105519-d764b950-e8fb-41e4-bc99-2f3846fc268b.png">

Sent order:

<img width="825" alt="Screen Shot 2021-11-10 at 12 35 41 PM" src="https://user-images.githubusercontent.com/1033194/141106240-3f14d357-32c7-4163-80e9-668eba29cda7.png">

**Comment by willbach** [comment]
This hasn't happened again since the fix went in.
