### ISSUE TITLE
Star Ops: font-size for secondary items should be 14px

### ISSUE THREAD

**Issue by jyng** [urbit/bridge#774]
`Residents` and `Requests` sections should should have font-size 14px

![image](https://user-images.githubusercontent.com/9557907/142266606-ffa17331-e5ec-484c-b6e7-f857d28bb5a4.png)

**Comment by nerveharp** [comment]
Confirmed 14px.

![image](https://user-images.githubusercontent.com/748181/144629961-93d6fb68-6149-4e8a-a4ef-7eb487a96065.png)
