### ISSUE TITLE
Spawn Star confirmation has incorrect font in status

### ISSUE THREAD

**Issue by nerveharp** [urbit/bridge#779]
When confirming that a L1 star spawning transaction is successfully complete, we display the confirmation message in a plain, unstyled `<span>`.

<img width="550" alt="image" src="https://user-images.githubusercontent.com/748181/142927153-d8dd8677-4086-478c-9d7a-402ff7f05e16.png">

**Comment by willbach** [comment]
@jyng what should this look like?

**Comment by jyng** [comment]
Ship names should always use our monospace font. And text should just be inter. This is case of it being unstyled here.

**Comment by nerveharp** [comment]
This is complete.
