### ISSUE TITLE
Visual adjustment needed in child points dropdown menu

### ISSUE THREAD

**Issue by nerveharp** [urbit/bridge#781]
I truly hate to be a UX boomer, but the child points list needs some kind of indication that the list exceeds the currently-visible subset. 

We can do this either with forcing the scrollbar (similar to the nicely styled one we have in Groups) or by making the visible pane artificially taller for and cutting off the "next" item in the list, giving a hint that there are more in the list. 

We can conditionally apply whatever visual solve for lists of 5+ items.

Current state:
<img width="339" alt="image" src="https://user-images.githubusercontent.com/748181/142928699-282bd008-a9aa-4a60-aac3-af1a0c0dcee0.png">

Proposed:
<img width="333" alt="image" src="https://user-images.githubusercontent.com/748181/142928754-ce658703-c4c9-4631-a784-ce6b70b72c29.png">

**Comment by willbach** [comment]
I'm gonna add a bit to the container so that the 5th point is cut off halfway
