### ISSUE TITLE
L2 planet invite flow: reached L2 transaction limit

### ISSUE THREAD

**Issue by nerveharp** [urbit/bridge#790]
When accepting an L2 planet invite through the usual flow, I received this error on the final screen.

1) I'm not sure why I've reached my transaction limit, but also
2) _undefined_ should be handled more gracefully.

<img width="788" alt="image" src="https://user-images.githubusercontent.com/748181/144077089-86aef477-c443-4a11-a547-4efc95c208fa.png">

**Comment by willbach** [comment]
ok thanks for this, the solution will be to just remove that check in this instance

**Comment by nerveharp** [comment]
No longer pops an error on final planet redemption screen.
