### ISSUE TITLE
"Insufficient ETH" error state

### ISSUE THREAD

**Issue by jyng** [urbit/bridge#793]
If you can figure this out in 1-2 days, that'd be great. If not, we should just move on.

**Comment by willbach** [comment]
@tomholford  here's what it should look like. I *think* the state for Eth transactions should have this available to check against the current wallet balance.

<img width="417" alt="Screen Shot 2021-11-30 at 2 38 34 PM" src="https://user-images.githubusercontent.com/7759384/144115894-047aee49-cdd6-454c-8371-78c47ebd3445.png">
e
