### ISSUE TITLE
Button text need to be centered

### ISSUE THREAD

**Issue by jyng** [urbit/bridge#794]

**Comment by nerveharp** [comment]
@jyng Any particular instances of non-centered button text we should be aware of?

**Comment by nerveharp** [comment]
Should be a universal law. Just a few examples:

![image](https://user-images.githubusercontent.com/748181/144893613-eabeb8fc-9746-4958-9f38-2d09922f0192.png)
![image](https://user-images.githubusercontent.com/748181/144893662-fde686e3-f0b9-495d-93ab-d755d5c7c634.png)
![image](https://user-images.githubusercontent.com/748181/144893705-32cb49b4-1880-4570-8626-6bef5d1d5c61.png)

**Comment by nerveharp** [comment]
Looking good.

![image](https://user-images.githubusercontent.com/748181/144925476-da775d03-23f5-49a2-97dc-883f0d6f71df.png)
