### ISSUE TITLE
Missing "Wallet Balance" in L1 Transaction Screens

### ISSUE THREAD

**Issue by jyng** [urbit/bridge#798]
All L1 Transaction Screens should display the Wallet Balance with an ability to refresh the balance
![image](https://user-images.githubusercontent.com/9557907/144295170-c13dbd14-e312-40ed-9f87-e3e9d9aabad6.png)

**Comment by nerveharp** [comment]
Confirmed wallet balance appearance in multiple L1 transaction screens.

![image](https://user-images.githubusercontent.com/748181/144628585-d2086c29-c690-4f13-8dc6-4f85e2526e94.png)
![image](https://user-images.githubusercontent.com/748181/144628649-9437322a-7af5-46e4-bd6e-3a667fb69ec7.png)
![image](https://user-images.githubusercontent.com/748181/144628718-3bcf8438-9b3a-4369-bd7c-b48daefcce34.png)
![image](https://user-images.githubusercontent.com/748181/144628755-58e42fcf-c4e4-4e9e-95b4-5deb9c2b3d56.png)

**Comment by jyng** [comment]
Missing Wallet Balance:
![image](https://user-images.githubusercontent.com/9557907/144894048-822a5f0b-27e3-4cbc-969e-e2329038956a.png)

**Comment by nerveharp** [comment]
Still a thing @jyng?
