### ISSUE TITLE
Should support keyfiles

### ISSUE THREAD

**Issue by philipcmonk** [urbit/bridge#8]
We should support importing keyfiles.  They're extremely common in practice, and they're the default for MyEtherWallet, geth, parity, and others.

They need a password to unlock.  keythereum has code you can look at to see how to process them.

**Comment by xhipster** [comment]
Consider import raw private keys. They are also are being used.

<img width="629" alt="screenshot 2019-01-20 at 11 08 05" src="https://user-images.githubusercontent.com/410789/51437205-beed9900-1ca3-11e9-9dcc-011b64b52d38.png">
