### ISSUE TITLE
UI: Top Bar Update

### ISSUE THREAD

**Issue by jyng** [urbit/bridge#800]
### Invite
Here are the different Invite States. I've shown numeration of Invites to showcase how the Invite Badge Number should behave. It has a 4px horizontal padding so it just should expand to the right as the numbers increase.
 
![Top Bar - Invite States](https://user-images.githubusercontent.com/9557907/144331788-082a26f8-19b1-414e-803e-f9e1e5ebf610.jpg)

### Dropdown
The dropdown state here shows Hover and Selected. Selected being the current Ship that is being displayed in the view. 
- The L2 badge should sit flush next to the dropdown. 
- It should say 'Spawn Planet' not 'Generate Invites'
- Let's remove the icon sigil inside the dropdown. Feels cleaner without it.
![Top Bar - Dropdown States](https://user-images.githubusercontent.com/9557907/144332666-bd3d8901-4761-456d-a5bf-449e8822a4ad.jpg)

**Comment by willbach** [comment]
@jyng this is very helpful, thanks!

Regarding this requirement: "It should say 'Spawn Planet' not 'Generate Invites'", I thought that the decision was to have it say "Generate Invites" for an L2 star, and "Spawn Planet/Star" for an L1 star or galaxy

**Comment by nerveharp** [comment]
![image](https://user-images.githubusercontent.com/748181/144629596-be9be884-8760-4d99-af96-51ec6c0760e0.png)

Looks good to me.
