### ISSUE TITLE
Transactions: Overflow scroll horizontal spacing

### ISSUE THREAD

**Issue by jyng** [urbit/bridge#801]
There shouldn't be any extra spacing between the scroll box and the top and bottom of the container. Detailed with red arrows below.
![UI Bug_ Overflow Spacing](https://user-images.githubusercontent.com/9557907/144333815-01af609a-ba2c-4a8d-8a15-49591af403d1.jpg)

**Comment by nerveharp** [comment]
![image](https://user-images.githubusercontent.com/748181/144629711-155bdce6-b9cb-4947-8ce5-ae0f5a3a2002.png)

Looks good to me.
