### ISSUE TITLE
Reskin the sub-OS and sub-ID screens (TODO: Sigil)

### ISSUE THREAD

**Issue by nerveharp** [urbit/bridge#809]
All child screens should follow the same general design (light gray border container with rounded corners; screen title set in bold and separated from content by horizontal line).

**Comment by nerveharp** [comment]
Bringing this back out of "Done" as the Sigil view does not match the other sub-screens:
- Missing the gray 8px-rounded frame
- Showing the ETH balance on a non-transaction screen

![image](https://user-images.githubusercontent.com/748181/144637591-4efbd7b9-4663-4f68-8a81-914887ad83bc.png)

**Comment by willbach** [comment]
The reskin:

<img width="580" alt="Screen Shot 2021-12-04 at 4 02 01 PM" src="https://user-images.githubusercontent.com/7759384/144724470-2176f6b1-5689-4874-a117-5e1295f21bd2.png">

**Comment by nerveharp** [comment]
Looking good!
