### ISSUE TITLE
npm run release doesn't do npm install

### ISSUE THREAD

**Issue by Fang-** [urbit/bridge#81]
Can it? Should it?

This bit me during release deployment today. The checkout I was working in did not have the `package.json`-specified version of some dependency installed, which broke something in the release build.

**Comment by jtobin** [comment]
Good catch.  Ideally bridge should have a test suite that auto-runs before the build, which would presumably catch weirdness like that.  But!  Given it doesn't, I think it's reasonable to replace the "release" field in `package.json` with:

```
    "release": "npm install && npm run build && npm run checksum && npm run zip",
```
