### ISSUE TITLE
L2 planet: escaping sponsor UI unresponsive/empty

### ISSUE THREAD

**Issue by nerveharp** [urbit/bridge#810]
**Describe the bug:**

**To reproduce:**
1. Log in to https://bridge-dev.urbit.org/ as `~hacluc-lanmyl` with Master Ticket `~sigfel-ragleb-datnux-napdul`
2. Click on "OS."
3. Click "Change" next to the current sponsor (`~hidzod`, if nothing has changed).
4. Enter `~morzod` and click "Request New Sponsor."
5. See that UI does nothing.
6. Navigate back twice to the planet's home screen.
7. Observe the stacked roller queue (from clicking the button a million times, presumably) with empty label.

**Expected behavior:**
1. The UI should confirm that I requested to escape `~hidzod` to `~marzod`.
2. As a result, I should not be able to click that button a million times.
3. The roller queue on the home screen should have some kind of text in it.

**Screenshot or console log:**
![image](https://user-images.githubusercontent.com/748181/144640194-2a4e0972-6b47-4a6c-92c8-d40be13ddc35.png)

![image](https://user-images.githubusercontent.com/748181/144639261-6160cc59-fceb-4156-8ac0-f7e9cde207a7.png)

**Ethereum network:**
Ropsten

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Firefox 94.0.2 (64-bit)

**Login method (please complete the following information):**
Master Ticket (see above)

**Comment by yosoyubik** [comment]
it looks like the transactions failed (note that they seem to be coming from different addresses):

<img width="884" alt="Screen Shot 2021-12-04 at 3 50 48 PM" src="https://user-images.githubusercontent.com/1033194/144714065-9fc6af00-93ff-4ee2-9197-c3ae05e2de79.png">


<img width="875" alt="Screen Shot 2021-12-04 at 3 51 15 PM" src="https://user-images.githubusercontent.com/1033194/144714068-15f00efb-e84e-4cdf-80e4-2c1ad850bbae.png">


<img width="1084" alt="Screen Shot 2021-12-04 at 3 53 22 PM" src="https://user-images.githubusercontent.com/1033194/144714089-47203f01-32a9-43ab-a2ba-b85c55fe04f1.png">

<img width="1069" alt="Screen Shot 2021-12-04 at 3 53 09 PM" src="https://user-images.githubusercontent.com/1033194/144714095-4057d5b5-5582-4736-bc03-eb4209f1d866.png">

**Comment by nerveharp** [comment]
Away we go, from `~marzod` back to `~hidzod`.

![image](https://user-images.githubusercontent.com/748181/144875894-65b86952-3f7b-4a87-bd64-9c13b0b75aeb.png)
