### ISSUE TITLE
Planet escaping sponsor: new sponsor text field placeholder should be six characters

### ISSUE THREAD

**Issue by nerveharp** [urbit/bridge#811]
When escaping a star sponsor as a planet, I am prompted to enter a new star to escape to. Unfortunately, the input field suggests that I can set my sponsor to a planet. We should special-case the placeholder prop in this case to be simply `~sampel`.

![2021-12-03_11-41](https://user-images.githubusercontent.com/748181/144640400-9c9a0e56-3cc7-4d89-b5c9-6505d6d7b77e.png)

**Comment by nerveharp** [comment]
Much better.

![image](https://user-images.githubusercontent.com/748181/144875681-8a1ca721-d627-4436-9de0-1fea7c546309.png)

**Comment by willbach** [comment]
Moving this pack into "TODO" because I need to make the placeholder be 3 characters when it's a star changing its sponsor.
