### ISSUE TITLE
Different point list contents based on login method

### ISSUE THREAD

**Issue by nerveharp** [urbit/bridge#812]
When logging in as `~zod` with the Master Ticket, I see this list of points:
![image](https://user-images.githubusercontent.com/748181/144642070-3597d7a6-5c3d-4607-b656-1c61fee63eb6.png)

When logging in with the Recover Phrase (`benefit ... kitten`), I see this list of points:
![image](https://user-images.githubusercontent.com/748181/144642006-e4d032ef-c48e-4d64-a0ed-4e4d908b300b.png)

I would expect that these would be the same, no?

**Comment by willbach** [comment]
@nerveharp these are two different ownership wallets. Check the top of the dropdown and you'll see that the addresses are different. ~zod has 0x864 and the passphrase has 0x6de

**Comment by nerveharp** [comment]
Interesting, thank you. I guess I didn't realize the distinction, but that makes sense.
