### ISSUE TITLE
UI: Network Keys Screen

### ISSUE THREAD

**Issue by jyng** [urbit/bridge#822]
Screen here needs to be updated to new design
![Set Network Key](https://user-images.githubusercontent.com/9557907/144893097-42a15591-367c-447e-808e-344b0f9624d5.jpg)

**Comment by willbach** [comment]
Are we going with "Network Keys" everywhere? (instead of "Networking")

**Comment by jyng** [comment]
Yep, we should be saying Network Keys. More parity with other keys (Management, Spawn, etc)
Relatedly, it should be Vote Key and not Voting Key.

There was a Github Issue that opened, but I think it got archived.

**Comment by nerveharp** [comment]
Yes, we should use the infinitive rather than the present participle ("Network," "Vote"). 

@e-shee FYI

**Comment by willbach** [comment]
PR for this: https://github.com/urbit/bridge/pull/825/files

**Comment by willbach** [comment]
> Yes, we should use the infinitive rather than the present participle ("Network," "Vote").
> 
> @e-shee FYI

Azimuth uses "voting" in the contract methods like "setVotingProxy" just FYI
