### ISSUE TITLE
Add point-level indicators for pending L1 transactions (like migration)

### ISSUE THREAD

**Issue by willbach** [urbit/bridge#823]

**Comment by willbach** [comment]
@jyng @nerveharp this is what I've got:

<img width="472" alt="Screen Shot 2021-12-08 at 9 51 39 PM" src="https://user-images.githubusercontent.com/7759384/145325722-8f46d212-57c9-4409-a051-de4bc4b9053e.png">

**Comment by nerveharp** [comment]
![image](https://user-images.githubusercontent.com/748181/145470048-07a2e8d9-8166-4fc0-bd1f-98c070e85409.png)

Confirmed that I can see this as well. Etherscan link works. 

Awaiting spiritual stamp from @jyng

**Comment by jyng** [comment]
I was hoping that we could have some parity with the other transactions. In this design here, we can showcase the different states the transactions goes through.

![image](https://user-images.githubusercontent.com/9557907/145912054-28bc1194-59b5-4104-af66-c9752189ba1d.png)

**Comment by willbach** [comment]
I think there are 3 states for L1 transactions: Pending, Complete, and Failed. I'll see if I can get info from the roller for this, I might be able to. At the very least I can update the design to look like the Transactions screen.
