### ISSUE TITLE
Having previous release in repo root messes up npm run release

### ISSUE THREAD

**Issue by Fang-** [urbit/bridge#84]
And here I was wondering why the 1.2.0 release was so much bigger!

If you've done a release before, and haven't cleaned the old zip up, it'll include it in the new release .zip. In some cases this actually corrupts the new release zip somehow.

Releases should obviously be as sparse as possible.

**Comment by alexmatz** [comment]
why was this happening?

**Comment by Fang-** [comment]
I'm not entirely sure? The scripts defined in `package.json` seem to specify a small subset of files to include in the zip, so that's fine. I just checked, and `npm run build` doesn't seem to touch it either, nothing weird ends up in the `build` directory. Maybe my analysis of the issue is incorrect, but I definitely observed:
1. New release .zip is big and corrupted
2. Delete all release .zips from directory
3. `npm run release`
4. New release .zip has normal size and works fine
