### ISSUE TITLE
Login: WalletConnect -> Ledger Live (desktop) failure

### ISSUE THREAD

**Issue by nerveharp** [urbit/bridge#850]
@crrncllns and I were unable to make Ledger Live work through the WalletConnect login option.

**To reproduce:**
1. Preinstall the Ledger Live desktop app for your platform (@crrncllns was using a Mac with what I presume was the latest OS), unlock and pair the Ledger device, and ensure the thing works "normally."
2. Go to https://bridge-staging.urbit.org/
3. Select WalletConnect as the login option.
4. In the toggle at the top of the modal dialog, select "Desktop."
5. Select "Ledger Live."
6. Sign the transaction with Ledger Live.
7. Observe error.

![B30ED586-038B-44F8-9395-1B85B391A184](https://user-images.githubusercontent.com/748181/146205111-859026ff-6a7a-45cf-82cc-976418f93360.jpeg)

**Ethereum network:**
- Mainnet

**Desktop (please complete the following information):**
 - MacOS with Ledger device

**Login method (please complete the following information):**
- WalletConnect -> Desktop

**Comment by willbach** [comment]
This error looks like a problem elsewhere. This error is most commonly thrown when a contract address is incorrect due to the contract not existing on the network or the front end being pointed at the wrong network.

**Comment by willbach** [comment]
I can't reproduce with a Ledger Nano S using Ledger Live on MacOS. Worked fine for me.
