### ISSUE TITLE
Instructions unclear

### ISSUE THREAD

**Issue by boatbuilder2020** [urbit/bridge#88]
The instruction:

python3 -m http.server 5000 --bind 127.0.0.1 --directory build

Whats the directory build argument ? I'm in the bridge directory.
getting error:

server.py: error: unrecognized arguments: --directory build.

If I remove the --directory build from the command, the localhost shows just a bunch of files.

**Comment by jtobin** [comment]
This looks to be the same as #35, so I suspect your Python version is too old.

Can you check `python3 --version` and see if it's lower than `3.7.2`?

**Comment by belisarius222** [comment]
I hit this on my macbook too. I got around it by just cd'ing to the build
directory and running without the extra arg. Why don't we just change the
instructions to do that instead of using the --directory argument?

—
~rovnys-ricfer
https://urbit.org

**Comment by boatbuilder2020** [comment]
> This looks to be the same as #35, so I suspect your Python version is too old.
> 
> Can you check `python3 --version` and see if it's lower than `3.7.2`?

Its 3.5.2

Ubuntu software updater doesn't even see it, i'll update it this evening.

**Comment by boatbuilder2020** [comment]
Ok..

_:~/Desktop/bridge-master$ python3.7 --version
Python 3.7.2_

Note change in python programme name below:

_:~/Desktop/bridge-master$ python3.7 -m http.server 5000 --bind 127.0.0.1
Serving HTTP on 127.0.0.1 port 5000 (http://127.0.0.1:5000/) ...
127.0.0.1 - - [26/Mar/2019 19:50:22] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2019 19:50:30] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2019 19:50:31] code 404, message File not found
127.0.0.1 - - [26/Mar/2019 19:50:31] "GET /favicon.ico HTTP/1.1" 404 -_

End up with local host just showing the files again.

**Comment by boatbuilder2020** [comment]
Ok using a release rather then clone:

@sg13:~/Desktop/bridge-1.2.1$ python3.7 --version
Python 3.7.2
:~/Desktop/bridge-1.2.1$ python3.7 -m http.server 5000 --bind 127.0.0.1
Serving HTTP on 127.0.0.1 port 5000 (http://127.0.0.1:5000/) ...
127.0.0.1 - - [26/Mar/2019 21:00:12] "GET / HTTP/1.1" 200 -

**Comment by jtobin** [comment]
You should be able to use the `--directory` option now.  I.e., presumably

```
python3 -m http.server 5000 --bind 127.0.0.1 --directory build
```

should work.

**Comment by boatbuilder2020** [comment]
It doesn't.

Interestingly I can get to a development page on localhost:3000 from instructions at 
https://github.com/urbit/bridge/blob/master/README.md telling me to "npm run pilot" after some steps.
Closing out of that and then running:
` python3.7 -m http.server 5000 --bind 127.0.0.1 --directory build`

brings me to in firefox on localhost:5000

```
Secure Connection Failed

An error occurred during a connection to localhost:5000. SSL received a record that exceeded the maximum permissible length. Error code: SSL_ERROR_RX_RECORD_TOO_LONG 
```

**Comment by Fang-** [comment]
For the record: you should access that over `http://localhost:5000`, not `https://localhost:5000`. Note the difference: `http` vs `https`.

**Comment by boatbuilder2020** [comment]
Messaging in terminal
> :~/Desktop/bridge-1.2.1$ python3.7 -m http.server 5000 --bind 127.0.0.1 --directory build
> Serving HTTP on 127.0.0.1 port 5000 (http://127.0.0.1:5000/) ...
> 127.0.0.1 - - [27/Mar/2019 20:42:32] code 404, message File not found
> 127.0.0.1 - - [27/Mar/2019 20:42:32] "GET / HTTP/1.1" 404 -

Error response (in firefox) using http://localhost:5000 

> Error code: 404
> Message: File not found.
> Error code explanation: HTTPStatus.NOT_FOUND - Nothing matches the given URI.

**Comment by boatbuilder2020** [comment]
Ok i didn't use the correct release download again. Its working now.

**Comment by alexmatz** [comment]
@Fang- I'm a bit confused. has the "Python version was too old to support
  the --directory option used in the instructions for serving the app." issue been fixed?

**Comment by Fang-** [comment]
Not yet. For next release, we'll want to just tell people to `cd bridge-vx.x.x/build` and then run `python3` without the `--directory` option. Or, even better, not unnecessarily put things inside a `build` folder in the first place.
