### ISSUE TITLE
login: supplemental instructions for metamask <-> hw wallet?

### ISSUE THREAD

**Issue by nerveharp** [urbit/bridge#882]
In the new Bridge login paradigm, we do not support hardware wallets, EKS, or EPK directly and instead encourage everyone to use these wallets through Metamask interop.

![image](https://user-images.githubusercontent.com/748181/150656652-6ba0411d-ab2c-4311-a879-64e287bae35c.png)

This may pose an interesting and/or confusing hurdle for some users. We can either link to an external guide or write one on our own, but I propose (A) preparing a guide to perform this operation, and (B) linking to it in the explanatory modal with the following text in the second paragraph:

> Refer to our guide on how to use these wallets with Metamask.

**Comment by nerveharp** [comment]
Kicking to @e-shee for effort estimation.

**Comment by e-shee** [comment]
This reads to me like an ultimatum. I generally agree that we should advise on how to use hardware wallets, EKS, and EPK with our own guide, but the quickest solution would be to link to an external guide and swap later.

**Comment by nerveharp** [comment]
Sounds good -- here's Metamask's own guide: https://metamask.zendesk.com/hc/en-us/articles/360020394612-How-to-connect-a-Trezor-or-Ledger-Hardware-Wallet

**Comment by nerveharp** [comment]
fixed by urbit/bridge#883
