### ISSUE TITLE
copy when factory resetting a L2 planet does not tell you to wait for the timer

### ISSUE THREAD

**Issue by drbeefsupreme** [urbit/bridge#888]
Right now, when you factory reset a L2 planet, there is no indication that you need to wait until the next batch is submitted before you can boot with the new keyfile. You'll get a key mismatch error if you try to boot before the next batch is submitted. One of the users I onboarded to L2 ran into this and was confused. So we should instruct the user to wait until the timer elapsed before booting after a factory reset.

**Comment by nerveharp** [comment]
![image](https://user-images.githubusercontent.com/748181/150821122-9c582cd8-6c1b-4757-b2fc-e920126cbfd6.png)

**Comment by nerveharp** [comment]
Adjusted the copy to reflect (A) our switch to the term "bootfile," (B) the important notice about waiting until the L2 batch goes through, and (C) a note about deleting your old pier before doing so.

![image](https://user-images.githubusercontent.com/748181/150847305-1c32b48f-0759-4af9-babe-e69a0c8776e5.png)

@drbeefsupreme @e-shee Comments welcome.
