### ISSUE TITLE
Accept incoming transfer unavailable in offline mode

### ISSUE THREAD

**Issue by Fang-** [urbit/bridge#89]
It's greyed out in the point overview screen, but shouldn't I still be able to generate a transaction for that in offline mode, if I so choose?

<img width="411" alt="image" src="https://user-images.githubusercontent.com/3829764/54955261-141c8400-4f4d-11e9-9151-f29206bc4e62.png">

**Comment by jtobin** [comment]
Definitely.  I think it's just greyed out because we currently hit the network to check if the currently-auth'd address is a transfer proxy for the point, but that hardly seems necessary.  The `disabled` condition in the point view can probably just be changed to `online && !canAcceptTransfer`.

**Comment by c-johnson** [comment]
has this been done already? looks like disabled only checks canAcceptTransfer currently: https://github.com/urbit/bridge/blob/master/src/bridge/views/Point/Actions.js#L147

**Comment by alexmatz** [comment]
@Fang- do you know if this has been done already?

**Comment by Fang-** [comment]
<img width="398" alt="image" src="https://user-images.githubusercontent.com/3829764/55667781-3ffb0c00-5861-11e9-8440-0622577f05eb.png">

Oh no, it's getting worse. (^:

@c-johnson, that check ends up as `false` [here](https://github.com/urbit/bridge/blob/master/src/bridge/views/Point/Actions.js#L95). We'll want all of these checks to return `true` in the case of offline mode, regardless of values. [cancelTransfer](https://github.com/urbit/bridge/blob/master/src/bridge/views/Point/Actions.js#L152) has the right idea.

Also we'll need to think about how to do keyfile generation in offline mode. Probably just an input field for the revision number if logged in with an urbit wallet, falling back to the "pls reset" in all other cases?

**Comment by Fang-** [comment]
Bridge v2 has no offline mode. Closing.
