### ISSUE TITLE
Fix the Set Network Keys flow's completion screen

### ISSUE THREAD

**Issue by tomholford** [urbit/bridge#892]
1. Spawn an L1 star
2. Logout and log back in
3. Select the newly spawned point, go to OS > Set Network Keys
4. Go through the Set Network Keys flow; the TX will complete successfully, but the button will appear disabled (see screenshot)

![image](https://user-images.githubusercontent.com/16504501/150933201-e00df2c8-b69b-4eff-ae00-07f3c97bf4c7.png)

**Comment by jyng** [comment]
Ran into the same issue

**Comment by nerveharp** [comment]
To add additional context:
- @jyng was trying to boot an L1 ship
- he attempted to set his network keys for this new ship
- > https://etherscan.io/tx/0x18e92441248c778d3ec70d92e3b306f5caae026de575202f63e3fa3ed148acae
- the keyfile he got from `bridge-staging` is ~256 characters long (`0wbgE.[...].Fv0r5`) and although this is correct for L2 planets, he cannot boot the ship (see screenshot)
- he logged in to `bridge-prod` and retrieved the keyfile, which is ~128 characters long and works (`0w1g6Ki.[...].B-BY1`)

Somebody who understands `%keys` please help, my family is dying

**Comment by jyng** [comment]
lmaoo

**Comment by tomholford** [comment]
Attempted to reproduce the first issue last night, was unable to this time on `roller` with Ropsten. The landing screen for the Set Net Keys flow looks fine now.

Will close this ticket and open another re: the keys issue reported by @jyng

**Comment by drbeefsupreme** [comment]
I'm running into this again, on Ropsten. L1 Planet, star, star with L2 spawn proxy, and galaxy.
