### ISSUE TITLE
'pre-boot error: %not-keyed' when booting L1 planet with multikey

### ISSUE THREAD

**Issue by tomholford** [urbit/bridge#895]
[this was originally reported as a comment on #892, this creates a separate issue for it]

[originally posted by](https://github.com/urbit/bridge/issues/892#issuecomment-1021705815) @nerveharp:

> @jyng was trying to boot an L1 ship
> he attempted to set his network keys for this new ship
> https://etherscan.io/tx/0x18e92441248c778d3ec70d92e3b306f5caae026de575202f63e3fa3ed148acae
> 
> the keyfile he got from bridge-staging is ~256 characters long (0wbgE.[...].Fv0r5) and although this is correct for L2 planets, this is an L1 ship and he cannot boot (see screenshot)
> he logged in to bridge-prod and retrieved the keyfile, which is ~128 characters long and works (0w1g6Ki.[...].B-BY1)
> Somebody who understands %keys please help, my family is dying

![image](https://user-images.githubusercontent.com/16504501/151211402-cc43f722-62d7-4746-aa70-df54df9a10eb.png)

**Comment by nerveharp** [comment]
Paging @Fang- to help as needed.

**Comment by Fang-** [comment]
@tomholford any chance this is some variation of the off-by-one I thought I had spotted, as per our dms last week? Certainly old and new bridge not generating the same key is a little suspect.

**Comment by tomholford** [comment]
> @tomholford any chance this is some variation of the off-by-one I thought I had spotted, as per our dms last week? Certainly old and new bridge not generating the same key is a little suspect.

@Fang- I think you're onto something, going to investigate and report back later today

**Comment by tomholford** [comment]
@Fang- and I just had an out-of-band discussion, turns out the multikey format should only be available to users during the Activation flow. Otherwise, we should generate single keyfile format files elsewhere - e.g., in the Home view. We discussed how to refactor this using an "n-keyfile" generator that supports either case.

**Comment by rshtirmer** [comment]
Hi, I am running into this issue with an L1 planet I'm trying to set up. If anyone can provide support, that would be much appreciated!
