### ISSUE TITLE
management proxy cannot set networking keys for L2 planet using metamask

### ISSUE THREAD

**Issue by drbeefsupreme** [urbit/bridge#896]
**Describe the bug:**
When attempting to set the networking keys with a management proxy on an L2 planet logged in via Metamask (held on a Trezor), a spinner appears when you press "Reset Networking Keys", but there is no pop-up to sign any transaction and nothing further happens.

**To reproduce:**
1. Login to bridge-staging with a L2 planet's management proxy via Metamask (not sure if it has to be Metamask).
2. Navigate to the screen where you reset networking keys.
3. Click "Reset Networking Keys"

**Expected behavior:**
Networking keys are reset.

**Screenshot or console log:**
![https://datnut-pollen.nyc3.digitaloceanspaces.com/datnut-pollen/2022.1.26..21.18.34-keyfile.png](https://datnut-pollen.nyc3.digitaloceanspaces.com/datnut-pollen/2022.1.26..21.18.34-keyfile.png)

**Ethereum network:**
Mainnet

**Desktop (please complete the following information):**
 - Browser: Brave
 - OS: NixOS 21.11

**Login method (please complete the following information):**
Metamask

**Comment by tomholford** [comment]
@drbeefsupreme Just tried to reproduce this issue, and was unable to do so. Perhaps a recent change in the past couple weeks resolved it? 

Here are the steps I took:
1. Add the Dev mnemonic to Brave Wallet
2. Login and select ~havfyr-ritdex
3. Navigate to ID and verify the MGMT proxy is set
4. Navigate to Home > OS and reset keys

**Comment by nerveharp** [comment]
@tomholford @arthyn This is not resolved on Ropsten or mainnet. I attempted the following:

1. Sign in to Bridge via Metamask.
2. Set the network keys by going into this section and clicking "Reset Network Keys."
3. No action, no confirmation, no request sent.

![image](https://user-images.githubusercontent.com/748181/153729097-fe14f206-e413-4b65-80bb-12377b5c1112.png)

**Comment by nerveharp** [comment]
Fixed by urbit/bridge#963
