### ISSUE TITLE
Bridge wrongly says transaction limit reached when galaxy accepting sponsorship request

### ISSUE THREAD

**Issue by drbeefsupreme** [urbit/bridge#898]
**Describe the bug:**
`~mibper`, a L2 star, sent a sponsorship request to `~rut`. I went to accept it from the management proxy, but was informed that my transaction limit had been reached. I have never done any L2 transactions with this address (nor the ownership address), so I should have been able to do it.

Not testing it with the ownership proxy since its in cold storage.

Not sure if this is specific to galaxies or also applies to stars accepting planets.

**To reproduce:**
1. Login with management proxy on a galaxy with a sponsor request.
2. Go to accept the sponsorship request.

**Expected behavior:**
Be able to accept a sponsor when under the transaction limit.

**Screenshot or console log:**
![sponsorship](https://datnut-pollen.nyc3.digitaloceanspaces.com/datnut-pollen/2022.1.27..16.48.27-2022-01-27_11-48.png)

![tx](https://datnut-pollen.nyc3.digitaloceanspaces.com/datnut-pollen/2022.1.27..17.01.06-2022-01-27_12-00.png)

**Ethereum network:**
Mainnet

**Desktop (please complete the following information):**
 - Browser: Brave

**Login method (please complete the following information):**
Trezor via Metamask

**Comment by yosoyubik** [comment]
The roller seems to give the right answer for ~rut's quota, but Bridge might be using other methods?
<img width="362" alt="Screen Shot 2022-01-27 at 6 04 40 PM" src="https://user-images.githubusercontent.com/1033194/151407942-a1fea479-e4e0-4dd6-bc7e-c5e3692412d8.png">
<img width="907" alt="Screen Shot 2022-01-27 at 6 03 37 PM" src="https://user-images.githubusercontent.com/1033194/151407968-1ef51b60-9886-41f6-a475-5ae2ad6b44de.png">

**Comment by yosoyubik** [comment]
@tomholford confirmed on ropsten (you can see that on ~del
<img width="1708" alt="Screen Shot 2022-01-27 at 6 35 07 PM" src="https://user-images.githubusercontent.com/1033194/151413563-4b6eb4ee-0587-4b82-a1f8-c48380e8617f.png">

**Comment by tomholford** [comment]
Have a hunch that this might be related to #874 and #900. In short, we may need to refactor or extend the logic that determines what operations each point is capable of.

**Comment by drbeefsupreme** [comment]
closed by #902
