### ISSUE TITLE
New subdomain for new bridge version

### ISSUE THREAD

**Issue by nerveharp** [urbit/bridge#899]
Let's switch the `bridge-staging` subdomian to something more user-appropriate. We settled on `bridge-beta`.

**Comment by yosoyubik** [comment]
@Fang- has access to that (it should be the same IP as `bridge-staging.urbit.org`)

**Comment by Fang-** [comment]
DNS should be set. You're gonna need a new SSL cert though.

**Comment by yosoyubik** [comment]
https://bridge-beta.urbit.org/ is live now
