### ISSUE TITLE
When directly accessing Activation form, the form validation breaks for manually entered tickets

### ISSUE THREAD

**Issue by tacryt-socryp** [urbit/bridge#909]
**Describe the bug:**
I discovered that I could use the URL https://bridge-dev.urbit.org/#sampel-palnet-sampel-palnet to go directly to the ActivationForm while leaving the form field empty. Not sure why it works, but it does, and I require the functionality to build my Bridge activation flow. However, when I go to that URL, when I then enter in a valid ticket that works when accessing the activation form normally, I get the following error message:

co.js:137 Uncaught (in promise) Error: patp2dec: not a valid @p
    at Object.T [as patp2dec] (co.js:137)
    at ActivateCodeForm.tsx:100
    at ActivateCodeForm.tsx:124
    at c (runtime.js:63)
    at Generator._invoke (runtime.js:294)
    at Generator.next (runtime.js:119)
    at r (asyncToGenerator.js:3)
    at o (asyncToGenerator.js:25)

**Expected behavior:**
I expect to be able to go to a URL that shows only the activation ticket form, then enter in an activation ticket and then custody the planet.

**Screenshot or console log:**
<img width="1323" alt="Screen Shot 2022-02-01 at 4 12 59 PM" src="https://user-images.githubusercontent.com/1377557/152060277-4c57894b-1d8b-44ec-b3e9-d5d6f1da2cea.png">

**Ethereum network:**
Ropsten

**Comment by nerveharp** [comment]
@tomholford 99% sure this is in `lib/useImpliedTicket.ts`. No valid six-word activation codes are permitted to return through the `impliedPatp` function.

**Comment by nerveharp** [comment]
@q validation may be available here instead of @p.

**Comment by nerveharp** [comment]
@tacryt-socryp Would a dedicated `/activate` route help you in this case as well?

**Comment by tacryt-socryp** [comment]
Yes, definitely
