### ISSUE TITLE
Galaxy sees no requests despite star escaping to it

### ISSUE THREAD

**Issue by Fang-** [urbit/bridge#912]
On ropsten, I made ~pidnec request escape to ~len. This worked fine, and ~pidnec now shows the "cancel request" screen instead of "select a new sponser" one.

However, on ~len, it still says there are `0` requests. This is not correct.

Looking in current Bridge, the request shows up fine, and can be accepted or rejected.

**Comment by yosoyubik** [comment]
The roller shows that request:

`[p=~len q=[residents={} requests={~pidnec}]]`

**Comment by arthyn** [comment]
I think this was just timing, seems to be there now. A few that I tried also took a while.

**Comment by lukestiles** [comment]
Closing - appears to be related to needing to wait for the roller to complete the transaction.
