### ISSUE TITLE
login: shard/ticket field swap

### ISSUE THREAD

**Issue by nerveharp** [urbit/bridge#923]
via @Fang- 

On the master ticket login screen, when toggling "shards" mode, the shards fields should replace the master ticket field, rather than display alongside it. Either you have the full master ticket, or the shards, but not both.

![](https://user-images.githubusercontent.com/3829764/152068245-d130e84a-bbf0-4565-8c98-47bb300a5c6e.png)

**Comment by Fang-** [comment]
Oh, note also the subtly different styling of the "shard 3" field. The other ones had been clicked into already, but the last one hadn't. Not sure why that gives a different placeholder color, but it does.

**Comment by nerveharp** [comment]
Good catch, @Fang-. Thank you.
