### ISSUE TITLE
Network keys have been set screen should give copy-pasteable command

### ISSUE THREAD

**Issue by Fang-** [urbit/bridge#945]
![image](https://user-images.githubusercontent.com/3829764/152881723-fad36274-c9e4-4145-b42b-278d518f4496.png)

We should inline the keyfile_contents for ease of use. Keeping the download option alongside it is righteous, we do not know whether the user needs that instead or not.

Perhaps the "download keyfile" button on the OS overview page should allow selecting an alternative option, to "copy command", to match this. More questionable though.

**Comment by lukestiles** [comment]
Putting keys in the copy-paste buffer is generally not secure.

**Comment by Fang-** [comment]
Unless we tell users to do a much more complicated "copy the keyfile into clay" flow, they are going to have to put the keys into clipboard at _some_ point to do the required `|rekey` command.

In other words, I don't think we stand to lose any security here, we only stand to gain convenience. (I guess displaying the key on-screen is slightly less secure? But again, it will be on screen at some point...)

(We could do tricks like wiping the clipboard when bridge/this screen regains focus, to _gain_ a little bit of security, but that's probably pretty hit-or-miss.)
