### ISSUE TITLE
perf: reduce JS bundle size

### ISSUE THREAD

**Issue by tomholford** [urbit/bridge#958]
The production JS bundle is currently almost 10MB. This is unacceptable for users on slow connections.

![image](https://user-images.githubusercontent.com/16504501/153640472-c4c06ce3-df2f-48c3-a61e-0a8472cc184c.png)

Luckily, this can resolved with several approaches:
- [code-splitting / lazy-loading](https://reactjs.org/docs/code-splitting.html)
- auditing project dependencies
- gzipped responses (via Caddy)

**Comment by tomholford** [comment]
An update: @yosoyubik added gzip encoding to the dev Caddyfile, confirming that the JS sent over the wire went from ~9.5MB to ~2MB

**Comment by lukestiles** [comment]
Closing as fixed.
