### ISSUE TITLE
Need to support sponsorship actions

### ISSUE THREAD

**Issue by Fang-** [urbit/bridge#97]
For stars and planets: `escape()` and `cancelEscape()`,  
For galaxies and stars: `adopt()`, `reject()` and `detach()`

We can and should get this in for next big release.

**Comment by alexmatz** [comment]
let's get design on board

**Comment by loganallenc** [comment]
Can we please support this functionality??? @jyng @Fang- @vvisigoth

**Comment by liam-fitzgerald** [comment]
This is already in hosting-rc

**Comment by Fang-** [comment]
Supported since hosting-rc merge in #406.
