### ISSUE TITLE
Cannot Go Back After Accepting Transfer

### ISSUE THREAD

**Issue by robkorn** [urbit/bridge#972]
Accepting L1 points (via Metamask) works properly, however after the tx has confirmed and I try to go back from the tx confirmation page, bridge just breaks, meaning to accept multiple points requires refreshing bridge after every single one is accepted, which is quite annoying/slow.

```
{"code":7979,"data":{}}
```

**Comment by tomholford** [comment]
![image](https://user-images.githubusercontent.com/16504501/154381390-748e883d-0024-4511-8700-d8ebe9e1f37f.png)

@robkorn Thanks for flagging this issue. Which back button triggered this issue? Or was it the browser back button?

**Comment by robkorn** [comment]
The one above "Accept Transfer". Also on another note I never ended up seeing this "X has been accepted." screen, though I think the longest I waited was like 30 seconds after the tx confirmed in metamask.

**Comment by arthyn** [comment]
@tomholford I think this one is similar to #973 in that the roller was timing out. Probably need a sweep on a lot of these to handle when the roller fails or times out.

**Comment by tomholford** [comment]
Per #973,  performance optimizations were deployed to roller and Bridge to resolve this issue.
