### ISSUE TITLE
login: galaxy cannot log in with 2/3 shards

### ISSUE THREAD

**Issue by nerveharp** [urbit/bridge#977]
A galaxy owner is reporting that they cannot log in to the new Bridge with 2 of the 3 password shards.

**Comment by vvisigoth** [comment]
Also hitting this. Plz to fix.

**Comment by mikegogulski** [comment]
Hell, I can't even log in with all 3 shards. Embarrassingly assive regression.

**Comment by tomholford** [comment]
Thanks for the update @mikegogulski.

Until we can fix this issue in Bridge 3.x, please use sunsetted Bridge:

https://bridge-sunset.urbit.org/

**Comment by tomholford** [comment]
@arthyn Okay to close this in light of #992 ?

**Comment by arthyn** [comment]
We just need to deploy it, but yes once it's deployed.

**Comment by nerveharp** [comment]
@tomholford @arthyn Anything blocking us from deploying, other than #549?
