### ISSUE TITLE
L2 invites: download CSV stuck generating

### ISSUE THREAD

**Issue by nerveharp** [urbit/bridge#978]
A report from userland:

> I'm not sure what's up. Tried it on beta and on the new, non-beta one. When I get to the download button, it's just not responsive. I click and nothing happens. Been like this for a few hours tonight. Maybe something with my browser, idk!

I cannot tell if this has been in play since we refactored this screen.

![0](https://user-images.githubusercontent.com/748181/154973339-fcb33177-302c-4f4b-8eae-b51c9a99547b.png)

As evidenced by the screenshot, we are talking about ~230 planet invites.

**Comment by arthyn** [comment]
Potentially fixed by #990 but need to investigate more

**Comment by nerveharp** [comment]
@arthyn This is good news, remaining optimistic.
