### ISSUE TITLE
When creating invites, the new invites only show up after log out and back in

### ISSUE THREAD

**Issue by jeremytunnell** [urbit/bridge#999]
I went to a star in bridge, created 10 invites, and submitted the transactions.  Then I got the countdown timer to the roller.  

Expected:  When the countdown is over, my invites show up (maybe a page refresh is okay).

Actual:  Must log out completely and back in to see the invites listed.

**Comment by lukestiles** [comment]
@jeremytunnell do you ercall how long you had to wait until the invites appeared? Was it a few minutes between generation and logging out, or much longer?

**Comment by jeremytunnell** [comment]
This appears to no longer be a bug.
